# CMake generated Testfile for 
# Source directory: /home/chlee/iree/runtime/src/iree/modules/check/test
# Build directory: /home/chlee/iree-build-riscv/runtime/src/iree/modules/check/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[iree/modules/check/test/check_vmvx_local-task_success.mlir]=] "/home/chlee/iree/build_tools/cmake/run_riscv_test.sh" "/home/chlee/iree-build-riscv/tools/iree-check-module" "--module=check_vmvx_local-task_success.mlir_module.vmfb" "--device=local-task")
set_tests_properties([=[iree/modules/check/test/check_vmvx_local-task_success.mlir]=] PROPERTIES  ENVIRONMENT "TEST_TMPDIR=/home/chlee/iree-build-riscv/test_tmpdir/iree/modules/check/test/check_vmvx_local-task_success.mlir_test_tmpdir;IREE_BINARY_DIR=/home/chlee/iree-build-riscv;IREE_DYLIB_EXT=.so;IREE_VULKAN_DISABLE=1;IREE_METAL_DISABLE=1" LABELS "test-type=check-test;driver=local-task;iree/modules/check/test" REQUIRED_FILES "check_vmvx_local-task_success.mlir_module.vmfb" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/chlee/iree/build_tools/cmake/iree_native_test.cmake;131;add_test;/home/chlee/iree/build_tools/cmake/iree_check_test.cmake;196;iree_native_test;/home/chlee/iree/build_tools/cmake/iree_check_test.cmake;269;iree_check_test;/home/chlee/iree/build_tools/cmake/iree_check_test.cmake;473;iree_check_single_backend_test_suite;/home/chlee/iree/runtime/src/iree/modules/check/test/CMakeLists.txt;29;iree_check_test_suite;/home/chlee/iree/runtime/src/iree/modules/check/test/CMakeLists.txt;0;")
add_test([=[iree/modules/check/test/check_vulkan-spirv_vulkan_success.mlir]=] "/home/chlee/iree/build_tools/cmake/run_riscv_test.sh" "/home/chlee/iree-build-riscv/tools/iree-check-module" "--module=check_vulkan-spirv_vulkan_success.mlir_module.vmfb" "--device=vulkan")
set_tests_properties([=[iree/modules/check/test/check_vulkan-spirv_vulkan_success.mlir]=] PROPERTIES  ENVIRONMENT "TEST_TMPDIR=/home/chlee/iree-build-riscv/test_tmpdir/iree/modules/check/test/check_vulkan-spirv_vulkan_success.mlir_test_tmpdir;IREE_BINARY_DIR=/home/chlee/iree-build-riscv;IREE_DYLIB_EXT=.so;IREE_VULKAN_DISABLE=1;IREE_METAL_DISABLE=1" LABELS "test-type=check-test;driver=vulkan;iree/modules/check/test" REQUIRED_FILES "check_vulkan-spirv_vulkan_success.mlir_module.vmfb" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/chlee/iree/build_tools/cmake/iree_native_test.cmake;131;add_test;/home/chlee/iree/build_tools/cmake/iree_check_test.cmake;196;iree_native_test;/home/chlee/iree/build_tools/cmake/iree_check_test.cmake;269;iree_check_test;/home/chlee/iree/build_tools/cmake/iree_check_test.cmake;473;iree_check_single_backend_test_suite;/home/chlee/iree/runtime/src/iree/modules/check/test/CMakeLists.txt;29;iree_check_test_suite;/home/chlee/iree/runtime/src/iree/modules/check/test/CMakeLists.txt;0;")
add_test([=[iree/modules/check/test/check_llvm-cpu_local-task_generic_success.mlir]=] "/home/chlee/iree/build_tools/cmake/run_riscv_test.sh" "/home/chlee/iree-build-riscv/tools/iree-check-module" "--module=check_llvm-cpu_local-task_generic_success.mlir_module.vmfb" "--device=local-task")
set_tests_properties([=[iree/modules/check/test/check_llvm-cpu_local-task_generic_success.mlir]=] PROPERTIES  ENVIRONMENT "TEST_TMPDIR=/home/chlee/iree-build-riscv/test_tmpdir/iree/modules/check/test/check_llvm-cpu_local-task_generic_success.mlir_test_tmpdir;IREE_BINARY_DIR=/home/chlee/iree-build-riscv;IREE_DYLIB_EXT=.so;IREE_VULKAN_DISABLE=1;IREE_METAL_DISABLE=1" LABELS "test-type=check-test;cpu_features=generic;driver=local-task;iree/modules/check/test" REQUIRED_FILES "check_llvm-cpu_local-task_generic_success.mlir_module.vmfb" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/chlee/iree/build_tools/cmake/iree_native_test.cmake;131;add_test;/home/chlee/iree/build_tools/cmake/iree_check_test.cmake;196;iree_native_test;/home/chlee/iree/build_tools/cmake/iree_check_test.cmake;269;iree_check_test;/home/chlee/iree/build_tools/cmake/iree_check_test.cmake;473;iree_check_single_backend_test_suite;/home/chlee/iree/runtime/src/iree/modules/check/test/CMakeLists.txt;29;iree_check_test_suite;/home/chlee/iree/runtime/src/iree/modules/check/test/CMakeLists.txt;0;")
add_test([=[iree/modules/check/test/check_failure_vmvx_local-task_failure.mlir]=] "/home/chlee/iree/build_tools/cmake/run_riscv_test.sh" "/home/chlee/iree-build-riscv/tools/iree-check-module" "--module=check_failure_vmvx_local-task_failure.mlir_module.vmfb" "--expect_failure" "--device=local-task")
set_tests_properties([=[iree/modules/check/test/check_failure_vmvx_local-task_failure.mlir]=] PROPERTIES  ENVIRONMENT "TEST_TMPDIR=/home/chlee/iree-build-riscv/test_tmpdir/iree/modules/check/test/check_failure_vmvx_local-task_failure.mlir_test_tmpdir;IREE_BINARY_DIR=/home/chlee/iree-build-riscv;IREE_DYLIB_EXT=.so;IREE_VULKAN_DISABLE=1;IREE_METAL_DISABLE=1" LABELS "test-type=check-test;driver=local-task;iree/modules/check/test" REQUIRED_FILES "check_failure_vmvx_local-task_failure.mlir_module.vmfb" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/chlee/iree/build_tools/cmake/iree_native_test.cmake;131;add_test;/home/chlee/iree/build_tools/cmake/iree_check_test.cmake;196;iree_native_test;/home/chlee/iree/build_tools/cmake/iree_check_test.cmake;269;iree_check_test;/home/chlee/iree/build_tools/cmake/iree_check_test.cmake;473;iree_check_single_backend_test_suite;/home/chlee/iree/runtime/src/iree/modules/check/test/CMakeLists.txt;38;iree_check_test_suite;/home/chlee/iree/runtime/src/iree/modules/check/test/CMakeLists.txt;0;")
add_test([=[iree/modules/check/test/check_failure_vulkan-spirv_vulkan_failure.mlir]=] "/home/chlee/iree/build_tools/cmake/run_riscv_test.sh" "/home/chlee/iree-build-riscv/tools/iree-check-module" "--module=check_failure_vulkan-spirv_vulkan_failure.mlir_module.vmfb" "--expect_failure" "--device=vulkan")
set_tests_properties([=[iree/modules/check/test/check_failure_vulkan-spirv_vulkan_failure.mlir]=] PROPERTIES  ENVIRONMENT "TEST_TMPDIR=/home/chlee/iree-build-riscv/test_tmpdir/iree/modules/check/test/check_failure_vulkan-spirv_vulkan_failure.mlir_test_tmpdir;IREE_BINARY_DIR=/home/chlee/iree-build-riscv;IREE_DYLIB_EXT=.so;IREE_VULKAN_DISABLE=1;IREE_METAL_DISABLE=1" LABELS "test-type=check-test;driver=vulkan;iree/modules/check/test" REQUIRED_FILES "check_failure_vulkan-spirv_vulkan_failure.mlir_module.vmfb" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/chlee/iree/build_tools/cmake/iree_native_test.cmake;131;add_test;/home/chlee/iree/build_tools/cmake/iree_check_test.cmake;196;iree_native_test;/home/chlee/iree/build_tools/cmake/iree_check_test.cmake;269;iree_check_test;/home/chlee/iree/build_tools/cmake/iree_check_test.cmake;473;iree_check_single_backend_test_suite;/home/chlee/iree/runtime/src/iree/modules/check/test/CMakeLists.txt;38;iree_check_test_suite;/home/chlee/iree/runtime/src/iree/modules/check/test/CMakeLists.txt;0;")
add_test([=[iree/modules/check/test/check_failure_llvm-cpu_local-task_generic_failure.mlir]=] "/home/chlee/iree/build_tools/cmake/run_riscv_test.sh" "/home/chlee/iree-build-riscv/tools/iree-check-module" "--module=check_failure_llvm-cpu_local-task_generic_failure.mlir_module.vmfb" "--expect_failure" "--device=local-task")
set_tests_properties([=[iree/modules/check/test/check_failure_llvm-cpu_local-task_generic_failure.mlir]=] PROPERTIES  ENVIRONMENT "TEST_TMPDIR=/home/chlee/iree-build-riscv/test_tmpdir/iree/modules/check/test/check_failure_llvm-cpu_local-task_generic_failure.mlir_test_tmpdir;IREE_BINARY_DIR=/home/chlee/iree-build-riscv;IREE_DYLIB_EXT=.so;IREE_VULKAN_DISABLE=1;IREE_METAL_DISABLE=1" LABELS "test-type=check-test;cpu_features=generic;driver=local-task;iree/modules/check/test" REQUIRED_FILES "check_failure_llvm-cpu_local-task_generic_failure.mlir_module.vmfb" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/chlee/iree/build_tools/cmake/iree_native_test.cmake;131;add_test;/home/chlee/iree/build_tools/cmake/iree_check_test.cmake;196;iree_native_test;/home/chlee/iree/build_tools/cmake/iree_check_test.cmake;269;iree_check_test;/home/chlee/iree/build_tools/cmake/iree_check_test.cmake;473;iree_check_single_backend_test_suite;/home/chlee/iree/runtime/src/iree/modules/check/test/CMakeLists.txt;38;iree_check_test_suite;/home/chlee/iree/runtime/src/iree/modules/check/test/CMakeLists.txt;0;")
