# CMake generated Testfile for 
# Source directory: /home/chlee/iree/runtime/src/iree/hal/drivers/vulkan/cts
# Build directory: /home/chlee/iree-build-riscv/runtime/src/iree/hal/drivers/vulkan/cts
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[iree/hal/drivers/vulkan/cts/vulkan_allocator_test]=] "/home/chlee/iree/build_tools/cmake/run_riscv_test.sh" "/home/chlee/iree-build-riscv/runtime/src/iree/hal/drivers/vulkan/cts/vulkan_allocator_test" "--gtest_filter=-SemaphoreTest.WaitThenFail:SemaphoreTest.FailThenWait:SemaphoreTest.MultiWaitThenFail:SemaphoreTest.DeviceMultiWaitThenFail:SemaphoreSubmissionTest.PropagateFailSignal:")
set_tests_properties([=[iree/hal/drivers/vulkan/cts/vulkan_allocator_test]=] PROPERTIES  ENVIRONMENT "TEST_TMPDIR=/home/chlee/iree-build-riscv/test_tmpdir/iree/hal/drivers/vulkan/cts/vulkan_allocator_test_test_tmpdir;IREE_BINARY_DIR=/home/chlee/iree-build-riscv;IREE_DYLIB_EXT=.so;IREE_VULKAN_DISABLE=1;IREE_METAL_DISABLE=1" LABELS "driver=vulkan;driver=vulkan;iree/hal/drivers/vulkan/cts" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/chlee/iree/build_tools/cmake/iree_cc_test.cmake;170;add_test;/home/chlee/iree/build_tools/cmake/iree_hal_cts_test_suite.cmake;198;iree_cc_test;/home/chlee/iree/runtime/src/iree/hal/drivers/vulkan/cts/CMakeLists.txt;24;iree_hal_cts_test_suite;/home/chlee/iree/runtime/src/iree/hal/drivers/vulkan/cts/CMakeLists.txt;0;")
add_test([=[iree/hal/drivers/vulkan/cts/vulkan_buffer_mapping_test]=] "/home/chlee/iree/build_tools/cmake/run_riscv_test.sh" "/home/chlee/iree-build-riscv/runtime/src/iree/hal/drivers/vulkan/cts/vulkan_buffer_mapping_test" "--gtest_filter=-SemaphoreTest.WaitThenFail:SemaphoreTest.FailThenWait:SemaphoreTest.MultiWaitThenFail:SemaphoreTest.DeviceMultiWaitThenFail:SemaphoreSubmissionTest.PropagateFailSignal:")
set_tests_properties([=[iree/hal/drivers/vulkan/cts/vulkan_buffer_mapping_test]=] PROPERTIES  ENVIRONMENT "TEST_TMPDIR=/home/chlee/iree-build-riscv/test_tmpdir/iree/hal/drivers/vulkan/cts/vulkan_buffer_mapping_test_test_tmpdir;IREE_BINARY_DIR=/home/chlee/iree-build-riscv;IREE_DYLIB_EXT=.so;IREE_VULKAN_DISABLE=1;IREE_METAL_DISABLE=1" LABELS "driver=vulkan;driver=vulkan;iree/hal/drivers/vulkan/cts" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/chlee/iree/build_tools/cmake/iree_cc_test.cmake;170;add_test;/home/chlee/iree/build_tools/cmake/iree_hal_cts_test_suite.cmake;198;iree_cc_test;/home/chlee/iree/runtime/src/iree/hal/drivers/vulkan/cts/CMakeLists.txt;24;iree_hal_cts_test_suite;/home/chlee/iree/runtime/src/iree/hal/drivers/vulkan/cts/CMakeLists.txt;0;")
add_test([=[iree/hal/drivers/vulkan/cts/vulkan_command_buffer_test]=] "/home/chlee/iree/build_tools/cmake/run_riscv_test.sh" "/home/chlee/iree-build-riscv/runtime/src/iree/hal/drivers/vulkan/cts/vulkan_command_buffer_test" "--gtest_filter=-SemaphoreTest.WaitThenFail:SemaphoreTest.FailThenWait:SemaphoreTest.MultiWaitThenFail:SemaphoreTest.DeviceMultiWaitThenFail:SemaphoreSubmissionTest.PropagateFailSignal:")
set_tests_properties([=[iree/hal/drivers/vulkan/cts/vulkan_command_buffer_test]=] PROPERTIES  ENVIRONMENT "TEST_TMPDIR=/home/chlee/iree-build-riscv/test_tmpdir/iree/hal/drivers/vulkan/cts/vulkan_command_buffer_test_test_tmpdir;IREE_BINARY_DIR=/home/chlee/iree-build-riscv;IREE_DYLIB_EXT=.so;IREE_VULKAN_DISABLE=1;IREE_METAL_DISABLE=1" LABELS "driver=vulkan;driver=vulkan;iree/hal/drivers/vulkan/cts" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/chlee/iree/build_tools/cmake/iree_cc_test.cmake;170;add_test;/home/chlee/iree/build_tools/cmake/iree_hal_cts_test_suite.cmake;198;iree_cc_test;/home/chlee/iree/runtime/src/iree/hal/drivers/vulkan/cts/CMakeLists.txt;24;iree_hal_cts_test_suite;/home/chlee/iree/runtime/src/iree/hal/drivers/vulkan/cts/CMakeLists.txt;0;")
add_test([=[iree/hal/drivers/vulkan/cts/vulkan_command_buffer_copy_buffer_test]=] "/home/chlee/iree/build_tools/cmake/run_riscv_test.sh" "/home/chlee/iree-build-riscv/runtime/src/iree/hal/drivers/vulkan/cts/vulkan_command_buffer_copy_buffer_test" "--gtest_filter=-SemaphoreTest.WaitThenFail:SemaphoreTest.FailThenWait:SemaphoreTest.MultiWaitThenFail:SemaphoreTest.DeviceMultiWaitThenFail:SemaphoreSubmissionTest.PropagateFailSignal:")
set_tests_properties([=[iree/hal/drivers/vulkan/cts/vulkan_command_buffer_copy_buffer_test]=] PROPERTIES  ENVIRONMENT "TEST_TMPDIR=/home/chlee/iree-build-riscv/test_tmpdir/iree/hal/drivers/vulkan/cts/vulkan_command_buffer_copy_buffer_test_test_tmpdir;IREE_BINARY_DIR=/home/chlee/iree-build-riscv;IREE_DYLIB_EXT=.so;IREE_VULKAN_DISABLE=1;IREE_METAL_DISABLE=1" LABELS "driver=vulkan;driver=vulkan;iree/hal/drivers/vulkan/cts" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/chlee/iree/build_tools/cmake/iree_cc_test.cmake;170;add_test;/home/chlee/iree/build_tools/cmake/iree_hal_cts_test_suite.cmake;198;iree_cc_test;/home/chlee/iree/runtime/src/iree/hal/drivers/vulkan/cts/CMakeLists.txt;24;iree_hal_cts_test_suite;/home/chlee/iree/runtime/src/iree/hal/drivers/vulkan/cts/CMakeLists.txt;0;")
add_test([=[iree/hal/drivers/vulkan/cts/vulkan_command_buffer_dispatch_test]=] "/home/chlee/iree/build_tools/cmake/run_riscv_test.sh" "/home/chlee/iree-build-riscv/runtime/src/iree/hal/drivers/vulkan/cts/vulkan_command_buffer_dispatch_test" "--gtest_filter=-SemaphoreTest.WaitThenFail:SemaphoreTest.FailThenWait:SemaphoreTest.MultiWaitThenFail:SemaphoreTest.DeviceMultiWaitThenFail:SemaphoreSubmissionTest.PropagateFailSignal:")
set_tests_properties([=[iree/hal/drivers/vulkan/cts/vulkan_command_buffer_dispatch_test]=] PROPERTIES  ENVIRONMENT "TEST_TMPDIR=/home/chlee/iree-build-riscv/test_tmpdir/iree/hal/drivers/vulkan/cts/vulkan_command_buffer_dispatch_test_test_tmpdir;IREE_BINARY_DIR=/home/chlee/iree-build-riscv;IREE_DYLIB_EXT=.so;IREE_VULKAN_DISABLE=1;IREE_METAL_DISABLE=1" LABELS "driver=vulkan;driver=vulkan;iree/hal/drivers/vulkan/cts" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/chlee/iree/build_tools/cmake/iree_cc_test.cmake;170;add_test;/home/chlee/iree/build_tools/cmake/iree_hal_cts_test_suite.cmake;198;iree_cc_test;/home/chlee/iree/runtime/src/iree/hal/drivers/vulkan/cts/CMakeLists.txt;24;iree_hal_cts_test_suite;/home/chlee/iree/runtime/src/iree/hal/drivers/vulkan/cts/CMakeLists.txt;0;")
add_test([=[iree/hal/drivers/vulkan/cts/vulkan_command_buffer_dispatch_constants_test]=] "/home/chlee/iree/build_tools/cmake/run_riscv_test.sh" "/home/chlee/iree-build-riscv/runtime/src/iree/hal/drivers/vulkan/cts/vulkan_command_buffer_dispatch_constants_test" "--gtest_filter=-SemaphoreTest.WaitThenFail:SemaphoreTest.FailThenWait:SemaphoreTest.MultiWaitThenFail:SemaphoreTest.DeviceMultiWaitThenFail:SemaphoreSubmissionTest.PropagateFailSignal:")
set_tests_properties([=[iree/hal/drivers/vulkan/cts/vulkan_command_buffer_dispatch_constants_test]=] PROPERTIES  ENVIRONMENT "TEST_TMPDIR=/home/chlee/iree-build-riscv/test_tmpdir/iree/hal/drivers/vulkan/cts/vulkan_command_buffer_dispatch_constants_test_test_tmpdir;IREE_BINARY_DIR=/home/chlee/iree-build-riscv;IREE_DYLIB_EXT=.so;IREE_VULKAN_DISABLE=1;IREE_METAL_DISABLE=1" LABELS "driver=vulkan;driver=vulkan;iree/hal/drivers/vulkan/cts" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/chlee/iree/build_tools/cmake/iree_cc_test.cmake;170;add_test;/home/chlee/iree/build_tools/cmake/iree_hal_cts_test_suite.cmake;198;iree_cc_test;/home/chlee/iree/runtime/src/iree/hal/drivers/vulkan/cts/CMakeLists.txt;24;iree_hal_cts_test_suite;/home/chlee/iree/runtime/src/iree/hal/drivers/vulkan/cts/CMakeLists.txt;0;")
add_test([=[iree/hal/drivers/vulkan/cts/vulkan_command_buffer_fill_buffer_test]=] "/home/chlee/iree/build_tools/cmake/run_riscv_test.sh" "/home/chlee/iree-build-riscv/runtime/src/iree/hal/drivers/vulkan/cts/vulkan_command_buffer_fill_buffer_test" "--gtest_filter=-SemaphoreTest.WaitThenFail:SemaphoreTest.FailThenWait:SemaphoreTest.MultiWaitThenFail:SemaphoreTest.DeviceMultiWaitThenFail:SemaphoreSubmissionTest.PropagateFailSignal:")
set_tests_properties([=[iree/hal/drivers/vulkan/cts/vulkan_command_buffer_fill_buffer_test]=] PROPERTIES  ENVIRONMENT "TEST_TMPDIR=/home/chlee/iree-build-riscv/test_tmpdir/iree/hal/drivers/vulkan/cts/vulkan_command_buffer_fill_buffer_test_test_tmpdir;IREE_BINARY_DIR=/home/chlee/iree-build-riscv;IREE_DYLIB_EXT=.so;IREE_VULKAN_DISABLE=1;IREE_METAL_DISABLE=1" LABELS "driver=vulkan;driver=vulkan;iree/hal/drivers/vulkan/cts" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/chlee/iree/build_tools/cmake/iree_cc_test.cmake;170;add_test;/home/chlee/iree/build_tools/cmake/iree_hal_cts_test_suite.cmake;198;iree_cc_test;/home/chlee/iree/runtime/src/iree/hal/drivers/vulkan/cts/CMakeLists.txt;24;iree_hal_cts_test_suite;/home/chlee/iree/runtime/src/iree/hal/drivers/vulkan/cts/CMakeLists.txt;0;")
add_test([=[iree/hal/drivers/vulkan/cts/vulkan_command_buffer_update_buffer_test]=] "/home/chlee/iree/build_tools/cmake/run_riscv_test.sh" "/home/chlee/iree-build-riscv/runtime/src/iree/hal/drivers/vulkan/cts/vulkan_command_buffer_update_buffer_test" "--gtest_filter=-SemaphoreTest.WaitThenFail:SemaphoreTest.FailThenWait:SemaphoreTest.MultiWaitThenFail:SemaphoreTest.DeviceMultiWaitThenFail:SemaphoreSubmissionTest.PropagateFailSignal:")
set_tests_properties([=[iree/hal/drivers/vulkan/cts/vulkan_command_buffer_update_buffer_test]=] PROPERTIES  ENVIRONMENT "TEST_TMPDIR=/home/chlee/iree-build-riscv/test_tmpdir/iree/hal/drivers/vulkan/cts/vulkan_command_buffer_update_buffer_test_test_tmpdir;IREE_BINARY_DIR=/home/chlee/iree-build-riscv;IREE_DYLIB_EXT=.so;IREE_VULKAN_DISABLE=1;IREE_METAL_DISABLE=1" LABELS "driver=vulkan;driver=vulkan;iree/hal/drivers/vulkan/cts" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/chlee/iree/build_tools/cmake/iree_cc_test.cmake;170;add_test;/home/chlee/iree/build_tools/cmake/iree_hal_cts_test_suite.cmake;198;iree_cc_test;/home/chlee/iree/runtime/src/iree/hal/drivers/vulkan/cts/CMakeLists.txt;24;iree_hal_cts_test_suite;/home/chlee/iree/runtime/src/iree/hal/drivers/vulkan/cts/CMakeLists.txt;0;")
add_test([=[iree/hal/drivers/vulkan/cts/vulkan_driver_test]=] "/home/chlee/iree/build_tools/cmake/run_riscv_test.sh" "/home/chlee/iree-build-riscv/runtime/src/iree/hal/drivers/vulkan/cts/vulkan_driver_test" "--gtest_filter=-SemaphoreTest.WaitThenFail:SemaphoreTest.FailThenWait:SemaphoreTest.MultiWaitThenFail:SemaphoreTest.DeviceMultiWaitThenFail:SemaphoreSubmissionTest.PropagateFailSignal:")
set_tests_properties([=[iree/hal/drivers/vulkan/cts/vulkan_driver_test]=] PROPERTIES  ENVIRONMENT "TEST_TMPDIR=/home/chlee/iree-build-riscv/test_tmpdir/iree/hal/drivers/vulkan/cts/vulkan_driver_test_test_tmpdir;IREE_BINARY_DIR=/home/chlee/iree-build-riscv;IREE_DYLIB_EXT=.so;IREE_VULKAN_DISABLE=1;IREE_METAL_DISABLE=1" LABELS "driver=vulkan;driver=vulkan;iree/hal/drivers/vulkan/cts" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/chlee/iree/build_tools/cmake/iree_cc_test.cmake;170;add_test;/home/chlee/iree/build_tools/cmake/iree_hal_cts_test_suite.cmake;198;iree_cc_test;/home/chlee/iree/runtime/src/iree/hal/drivers/vulkan/cts/CMakeLists.txt;24;iree_hal_cts_test_suite;/home/chlee/iree/runtime/src/iree/hal/drivers/vulkan/cts/CMakeLists.txt;0;")
add_test([=[iree/hal/drivers/vulkan/cts/vulkan_event_test]=] "/home/chlee/iree/build_tools/cmake/run_riscv_test.sh" "/home/chlee/iree-build-riscv/runtime/src/iree/hal/drivers/vulkan/cts/vulkan_event_test" "--gtest_filter=-SemaphoreTest.WaitThenFail:SemaphoreTest.FailThenWait:SemaphoreTest.MultiWaitThenFail:SemaphoreTest.DeviceMultiWaitThenFail:SemaphoreSubmissionTest.PropagateFailSignal:")
set_tests_properties([=[iree/hal/drivers/vulkan/cts/vulkan_event_test]=] PROPERTIES  ENVIRONMENT "TEST_TMPDIR=/home/chlee/iree-build-riscv/test_tmpdir/iree/hal/drivers/vulkan/cts/vulkan_event_test_test_tmpdir;IREE_BINARY_DIR=/home/chlee/iree-build-riscv;IREE_DYLIB_EXT=.so;IREE_VULKAN_DISABLE=1;IREE_METAL_DISABLE=1" LABELS "driver=vulkan;driver=vulkan;iree/hal/drivers/vulkan/cts" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/chlee/iree/build_tools/cmake/iree_cc_test.cmake;170;add_test;/home/chlee/iree/build_tools/cmake/iree_hal_cts_test_suite.cmake;198;iree_cc_test;/home/chlee/iree/runtime/src/iree/hal/drivers/vulkan/cts/CMakeLists.txt;24;iree_hal_cts_test_suite;/home/chlee/iree/runtime/src/iree/hal/drivers/vulkan/cts/CMakeLists.txt;0;")
add_test([=[iree/hal/drivers/vulkan/cts/vulkan_executable_cache_test]=] "/home/chlee/iree/build_tools/cmake/run_riscv_test.sh" "/home/chlee/iree-build-riscv/runtime/src/iree/hal/drivers/vulkan/cts/vulkan_executable_cache_test" "--gtest_filter=-SemaphoreTest.WaitThenFail:SemaphoreTest.FailThenWait:SemaphoreTest.MultiWaitThenFail:SemaphoreTest.DeviceMultiWaitThenFail:SemaphoreSubmissionTest.PropagateFailSignal:")
set_tests_properties([=[iree/hal/drivers/vulkan/cts/vulkan_executable_cache_test]=] PROPERTIES  ENVIRONMENT "TEST_TMPDIR=/home/chlee/iree-build-riscv/test_tmpdir/iree/hal/drivers/vulkan/cts/vulkan_executable_cache_test_test_tmpdir;IREE_BINARY_DIR=/home/chlee/iree-build-riscv;IREE_DYLIB_EXT=.so;IREE_VULKAN_DISABLE=1;IREE_METAL_DISABLE=1" LABELS "driver=vulkan;driver=vulkan;iree/hal/drivers/vulkan/cts" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/chlee/iree/build_tools/cmake/iree_cc_test.cmake;170;add_test;/home/chlee/iree/build_tools/cmake/iree_hal_cts_test_suite.cmake;198;iree_cc_test;/home/chlee/iree/runtime/src/iree/hal/drivers/vulkan/cts/CMakeLists.txt;24;iree_hal_cts_test_suite;/home/chlee/iree/runtime/src/iree/hal/drivers/vulkan/cts/CMakeLists.txt;0;")
add_test([=[iree/hal/drivers/vulkan/cts/vulkan_file_test]=] "/home/chlee/iree/build_tools/cmake/run_riscv_test.sh" "/home/chlee/iree-build-riscv/runtime/src/iree/hal/drivers/vulkan/cts/vulkan_file_test" "--gtest_filter=-SemaphoreTest.WaitThenFail:SemaphoreTest.FailThenWait:SemaphoreTest.MultiWaitThenFail:SemaphoreTest.DeviceMultiWaitThenFail:SemaphoreSubmissionTest.PropagateFailSignal:")
set_tests_properties([=[iree/hal/drivers/vulkan/cts/vulkan_file_test]=] PROPERTIES  ENVIRONMENT "TEST_TMPDIR=/home/chlee/iree-build-riscv/test_tmpdir/iree/hal/drivers/vulkan/cts/vulkan_file_test_test_tmpdir;IREE_BINARY_DIR=/home/chlee/iree-build-riscv;IREE_DYLIB_EXT=.so;IREE_VULKAN_DISABLE=1;IREE_METAL_DISABLE=1" LABELS "driver=vulkan;driver=vulkan;iree/hal/drivers/vulkan/cts" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/chlee/iree/build_tools/cmake/iree_cc_test.cmake;170;add_test;/home/chlee/iree/build_tools/cmake/iree_hal_cts_test_suite.cmake;198;iree_cc_test;/home/chlee/iree/runtime/src/iree/hal/drivers/vulkan/cts/CMakeLists.txt;24;iree_hal_cts_test_suite;/home/chlee/iree/runtime/src/iree/hal/drivers/vulkan/cts/CMakeLists.txt;0;")
add_test([=[iree/hal/drivers/vulkan/cts/vulkan_semaphore_test]=] "/home/chlee/iree/build_tools/cmake/run_riscv_test.sh" "/home/chlee/iree-build-riscv/runtime/src/iree/hal/drivers/vulkan/cts/vulkan_semaphore_test" "--gtest_filter=-SemaphoreTest.WaitThenFail:SemaphoreTest.FailThenWait:SemaphoreTest.MultiWaitThenFail:SemaphoreTest.DeviceMultiWaitThenFail:SemaphoreSubmissionTest.PropagateFailSignal:")
set_tests_properties([=[iree/hal/drivers/vulkan/cts/vulkan_semaphore_test]=] PROPERTIES  ENVIRONMENT "TEST_TMPDIR=/home/chlee/iree-build-riscv/test_tmpdir/iree/hal/drivers/vulkan/cts/vulkan_semaphore_test_test_tmpdir;IREE_BINARY_DIR=/home/chlee/iree-build-riscv;IREE_DYLIB_EXT=.so;IREE_VULKAN_DISABLE=1;IREE_METAL_DISABLE=1" LABELS "driver=vulkan;driver=vulkan;iree/hal/drivers/vulkan/cts" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/chlee/iree/build_tools/cmake/iree_cc_test.cmake;170;add_test;/home/chlee/iree/build_tools/cmake/iree_hal_cts_test_suite.cmake;198;iree_cc_test;/home/chlee/iree/runtime/src/iree/hal/drivers/vulkan/cts/CMakeLists.txt;24;iree_hal_cts_test_suite;/home/chlee/iree/runtime/src/iree/hal/drivers/vulkan/cts/CMakeLists.txt;0;")
