# CMake generated Testfile for 
# Source directory: /home/chlee/iree/runtime/src/iree/base/internal
# Build directory: /home/chlee/iree-build-riscv/runtime/src/iree/base/internal
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[iree/base/internal/atomics_test]=] "/home/chlee/iree/build_tools/cmake/run_riscv_test.sh" "/home/chlee/iree-build-riscv/runtime/src/iree/base/internal/atomics_test")
set_tests_properties([=[iree/base/internal/atomics_test]=] PROPERTIES  ENVIRONMENT "TEST_TMPDIR=/home/chlee/iree-build-riscv/test_tmpdir/iree/base/internal/atomics_test_test_tmpdir;IREE_BINARY_DIR=/home/chlee/iree-build-riscv;IREE_DYLIB_EXT=.so;IREE_VULKAN_DISABLE=1;IREE_METAL_DISABLE=1" LABELS "iree/base/internal" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/chlee/iree/build_tools/cmake/iree_cc_test.cmake;170;add_test;/home/chlee/iree/runtime/src/iree/base/internal/CMakeLists.txt;31;iree_cc_test;/home/chlee/iree/runtime/src/iree/base/internal/CMakeLists.txt;0;")
add_test([=[iree/base/internal/math_test]=] "/home/chlee/iree/build_tools/cmake/run_riscv_test.sh" "/home/chlee/iree-build-riscv/runtime/src/iree/base/internal/math_test")
set_tests_properties([=[iree/base/internal/math_test]=] PROPERTIES  ENVIRONMENT "TEST_TMPDIR=/home/chlee/iree-build-riscv/test_tmpdir/iree/base/internal/math_test_test_tmpdir;IREE_BINARY_DIR=/home/chlee/iree-build-riscv;IREE_DYLIB_EXT=.so;IREE_VULKAN_DISABLE=1;IREE_METAL_DISABLE=1" LABELS "iree/base/internal" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/chlee/iree/build_tools/cmake/iree_cc_test.cmake;170;add_test;/home/chlee/iree/runtime/src/iree/base/internal/CMakeLists.txt;43;iree_cc_test;/home/chlee/iree/runtime/src/iree/base/internal/CMakeLists.txt;0;")
add_test([=[iree/base/internal/atomic_slist_test]=] "/home/chlee/iree/build_tools/cmake/run_riscv_test.sh" "/home/chlee/iree-build-riscv/runtime/src/iree/base/internal/atomic_slist_test")
set_tests_properties([=[iree/base/internal/atomic_slist_test]=] PROPERTIES  ENVIRONMENT "TEST_TMPDIR=/home/chlee/iree-build-riscv/test_tmpdir/iree/base/internal/atomic_slist_test_test_tmpdir;IREE_BINARY_DIR=/home/chlee/iree-build-riscv;IREE_DYLIB_EXT=.so;IREE_VULKAN_DISABLE=1;IREE_METAL_DISABLE=1" LABELS "iree/base/internal" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/chlee/iree/build_tools/cmake/iree_cc_test.cmake;170;add_test;/home/chlee/iree/runtime/src/iree/base/internal/CMakeLists.txt;83;iree_cc_test;/home/chlee/iree/runtime/src/iree/base/internal/CMakeLists.txt;0;")
add_test([=[iree/base/internal/file_io_test]=] "/home/chlee/iree/build_tools/cmake/run_riscv_test.sh" "/home/chlee/iree-build-riscv/runtime/src/iree/base/internal/file_io_test")
set_tests_properties([=[iree/base/internal/file_io_test]=] PROPERTIES  ENVIRONMENT "TEST_TMPDIR=/home/chlee/iree-build-riscv/test_tmpdir/iree/base/internal/file_io_test_test_tmpdir;IREE_BINARY_DIR=/home/chlee/iree-build-riscv;IREE_DYLIB_EXT=.so;IREE_VULKAN_DISABLE=1;IREE_METAL_DISABLE=1" LABELS "requires-filesystem;iree/base/internal" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/chlee/iree/build_tools/cmake/iree_cc_test.cmake;170;add_test;/home/chlee/iree/runtime/src/iree/base/internal/CMakeLists.txt;137;iree_cc_test;/home/chlee/iree/runtime/src/iree/base/internal/CMakeLists.txt;0;")
add_test([=[iree/base/internal/fpu_state_benchmark_test]=] "/home/chlee/iree/build_tools/cmake/run_riscv_test.sh" "/home/chlee/iree-build-riscv/runtime/src/iree/base/internal/fpu_state_benchmark" "--benchmark_min_time=0")
set_tests_properties([=[iree/base/internal/fpu_state_benchmark_test]=] PROPERTIES  ENVIRONMENT "TEST_TMPDIR=/home/chlee/iree-build-riscv/test_tmpdir/iree/base/internal/fpu_state_benchmark_test_test_tmpdir;IREE_BINARY_DIR=/home/chlee/iree-build-riscv;IREE_DYLIB_EXT=.so;IREE_VULKAN_DISABLE=1;IREE_METAL_DISABLE=1" LABELS "iree/base/internal" REQUIRED_FILES "" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/chlee/iree/build_tools/cmake/iree_native_test.cmake;131;add_test;/home/chlee/iree/build_tools/cmake/iree_cc_binary_benchmark.cmake;72;iree_native_test;/home/chlee/iree/runtime/src/iree/base/internal/CMakeLists.txt;203;iree_cc_binary_benchmark;/home/chlee/iree/runtime/src/iree/base/internal/CMakeLists.txt;0;")
add_test([=[iree/base/internal/fpu_state_test]=] "/home/chlee/iree/build_tools/cmake/run_riscv_test.sh" "/home/chlee/iree-build-riscv/runtime/src/iree/base/internal/fpu_state_test")
set_tests_properties([=[iree/base/internal/fpu_state_test]=] PROPERTIES  ENVIRONMENT "TEST_TMPDIR=/home/chlee/iree-build-riscv/test_tmpdir/iree/base/internal/fpu_state_test_test_tmpdir;IREE_BINARY_DIR=/home/chlee/iree-build-riscv;IREE_DYLIB_EXT=.so;IREE_VULKAN_DISABLE=1;IREE_METAL_DISABLE=1" LABELS "requires-dtz;iree/base/internal" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/chlee/iree/build_tools/cmake/iree_cc_test.cmake;170;add_test;/home/chlee/iree/runtime/src/iree/base/internal/CMakeLists.txt;216;iree_cc_test;/home/chlee/iree/runtime/src/iree/base/internal/CMakeLists.txt;0;")
add_test([=[iree/base/internal/path_test]=] "/home/chlee/iree/build_tools/cmake/run_riscv_test.sh" "/home/chlee/iree-build-riscv/runtime/src/iree/base/internal/path_test")
set_tests_properties([=[iree/base/internal/path_test]=] PROPERTIES  ENVIRONMENT "TEST_TMPDIR=/home/chlee/iree-build-riscv/test_tmpdir/iree/base/internal/path_test_test_tmpdir;IREE_BINARY_DIR=/home/chlee/iree-build-riscv;IREE_DYLIB_EXT=.so;IREE_VULKAN_DISABLE=1;IREE_METAL_DISABLE=1" LABELS "iree/base/internal" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/chlee/iree/build_tools/cmake/iree_cc_test.cmake;170;add_test;/home/chlee/iree/runtime/src/iree/base/internal/CMakeLists.txt;255;iree_cc_test;/home/chlee/iree/runtime/src/iree/base/internal/CMakeLists.txt;0;")
add_test([=[iree/base/internal/prng_test]=] "/home/chlee/iree/build_tools/cmake/run_riscv_test.sh" "/home/chlee/iree-build-riscv/runtime/src/iree/base/internal/prng_test")
set_tests_properties([=[iree/base/internal/prng_test]=] PROPERTIES  ENVIRONMENT "TEST_TMPDIR=/home/chlee/iree-build-riscv/test_tmpdir/iree/base/internal/prng_test_test_tmpdir;IREE_BINARY_DIR=/home/chlee/iree-build-riscv;IREE_DYLIB_EXT=.so;IREE_VULKAN_DISABLE=1;IREE_METAL_DISABLE=1" LABELS "iree/base/internal" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/chlee/iree/build_tools/cmake/iree_cc_test.cmake;170;add_test;/home/chlee/iree/runtime/src/iree/base/internal/CMakeLists.txt;278;iree_cc_test;/home/chlee/iree/runtime/src/iree/base/internal/CMakeLists.txt;0;")
add_test([=[iree/base/internal/synchronization_benchmark_test]=] "/home/chlee/iree/build_tools/cmake/run_riscv_test.sh" "/home/chlee/iree-build-riscv/runtime/src/iree/base/internal/synchronization_benchmark" "--benchmark_min_time=0")
set_tests_properties([=[iree/base/internal/synchronization_benchmark_test]=] PROPERTIES  ENVIRONMENT "TEST_TMPDIR=/home/chlee/iree-build-riscv/test_tmpdir/iree/base/internal/synchronization_benchmark_test_test_tmpdir;IREE_BINARY_DIR=/home/chlee/iree-build-riscv;IREE_DYLIB_EXT=.so;IREE_VULKAN_DISABLE=1;IREE_METAL_DISABLE=1" LABELS "iree/base/internal" REQUIRED_FILES "" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/chlee/iree/build_tools/cmake/iree_native_test.cmake;131;add_test;/home/chlee/iree/build_tools/cmake/iree_cc_binary_benchmark.cmake;72;iree_native_test;/home/chlee/iree/runtime/src/iree/base/internal/CMakeLists.txt;314;iree_cc_binary_benchmark;/home/chlee/iree/runtime/src/iree/base/internal/CMakeLists.txt;0;")
add_test([=[iree/base/internal/synchronization_test]=] "/home/chlee/iree/build_tools/cmake/run_riscv_test.sh" "/home/chlee/iree-build-riscv/runtime/src/iree/base/internal/synchronization_test")
set_tests_properties([=[iree/base/internal/synchronization_test]=] PROPERTIES  ENVIRONMENT "TEST_TMPDIR=/home/chlee/iree-build-riscv/test_tmpdir/iree/base/internal/synchronization_test_test_tmpdir;IREE_BINARY_DIR=/home/chlee/iree-build-riscv;IREE_DYLIB_EXT=.so;IREE_VULKAN_DISABLE=1;IREE_METAL_DISABLE=1" LABELS "iree/base/internal" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/chlee/iree/build_tools/cmake/iree_cc_test.cmake;170;add_test;/home/chlee/iree/runtime/src/iree/base/internal/CMakeLists.txt;326;iree_cc_test;/home/chlee/iree/runtime/src/iree/base/internal/CMakeLists.txt;0;")
add_test([=[iree/base/internal/wait_handle_test]=] "/home/chlee/iree/build_tools/cmake/run_riscv_test.sh" "/home/chlee/iree-build-riscv/runtime/src/iree/base/internal/wait_handle_test")
set_tests_properties([=[iree/base/internal/wait_handle_test]=] PROPERTIES  ENVIRONMENT "TEST_TMPDIR=/home/chlee/iree-build-riscv/test_tmpdir/iree/base/internal/wait_handle_test_test_tmpdir;IREE_BINARY_DIR=/home/chlee/iree-build-riscv;IREE_DYLIB_EXT=.so;IREE_VULKAN_DISABLE=1;IREE_METAL_DISABLE=1" LABELS "iree/base/internal" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/chlee/iree/build_tools/cmake/iree_cc_test.cmake;170;add_test;/home/chlee/iree/runtime/src/iree/base/internal/CMakeLists.txt;373;iree_cc_test;/home/chlee/iree/runtime/src/iree/base/internal/CMakeLists.txt;0;")
add_test([=[iree/base/internal/threading_test]=] "/home/chlee/iree/build_tools/cmake/run_riscv_test.sh" "/home/chlee/iree-build-riscv/runtime/src/iree/base/internal/threading_test")
set_tests_properties([=[iree/base/internal/threading_test]=] PROPERTIES  ENVIRONMENT "TEST_TMPDIR=/home/chlee/iree-build-riscv/test_tmpdir/iree/base/internal/threading_test_test_tmpdir;IREE_BINARY_DIR=/home/chlee/iree-build-riscv;IREE_DYLIB_EXT=.so;IREE_VULKAN_DISABLE=1;IREE_METAL_DISABLE=1" LABELS "iree/base/internal" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/chlee/iree/build_tools/cmake/iree_cc_test.cmake;170;add_test;/home/chlee/iree/runtime/src/iree/base/internal/CMakeLists.txt;424;iree_cc_test;/home/chlee/iree/runtime/src/iree/base/internal/CMakeLists.txt;0;")
subdirs("flatcc")
