#ifndef DISPATCH_DEF_JSON_PRINTER_H
#define DISPATCH_DEF_JSON_PRINTER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#include "flatcc/flatcc_json_printer.h"
#include "flatcc/flatcc_prologue.h"

/*
 * Prints the default root table or struct from a buffer which must have
 * the schema declared file identifier, if any. It is also possible to
 * call the type specific `print_json_as_root` function wich accepts an
 * optional identifier (or 0) as argument. The printer `ctx` object must
 * be initialized with the appropriate output type, or it can be 0 which
 * defaults to stdout. NOTE: `ctx` is not generally allowed to be null, only
 * here for a simplified interface.
 */
static int dispatch_def_print_json(flatcc_json_printer_t *ctx, const char *buf, size_t bufsiz);

static void iree_instruments_DispatchFunctionDef_print_json_table(flatcc_json_printer_t *ctx, flatcc_json_printer_table_descriptor_t *td);
static void iree_instruments_DispatchSiteDef_print_json_table(flatcc_json_printer_t *ctx, flatcc_json_printer_table_descriptor_t *td);
static void iree_instruments_DispatchInstrumentDef_print_json_table(flatcc_json_printer_t *ctx, flatcc_json_printer_table_descriptor_t *td);

static void iree_instruments_DispatchFunctionDef_print_json_table(flatcc_json_printer_t *ctx, flatcc_json_printer_table_descriptor_t *td)
{
    flatcc_json_printer_string_field(ctx, td, 0, "name", 4);
    flatcc_json_printer_string_field(ctx, td, 1, "target", 6);
    flatcc_json_printer_string_field(ctx, td, 2, "layout", 6);
    flatcc_json_printer_string_field(ctx, td, 3, "source", 6);
}

static inline int iree_instruments_DispatchFunctionDef_print_json_as_root(flatcc_json_printer_t *ctx, const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_json_printer_table_as_root(ctx, buf, bufsiz, fid, iree_instruments_DispatchFunctionDef_print_json_table);
}

static void iree_instruments_DispatchSiteDef_print_json_table(flatcc_json_printer_t *ctx, flatcc_json_printer_table_descriptor_t *td)
{
    flatcc_json_printer_uint32_field(ctx, td, 0, "function", 8, UINT32_C(0));
}

static inline int iree_instruments_DispatchSiteDef_print_json_as_root(flatcc_json_printer_t *ctx, const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_json_printer_table_as_root(ctx, buf, bufsiz, fid, iree_instruments_DispatchSiteDef_print_json_table);
}

static void iree_instruments_DispatchInstrumentDef_print_json_table(flatcc_json_printer_t *ctx, flatcc_json_printer_table_descriptor_t *td)
{
    flatcc_json_printer_uint32_field(ctx, td, 0, "version", 7, UINT32_C(0));
    flatcc_json_printer_uint32_field(ctx, td, 1, "flags", 5, UINT32_C(0));
    flatcc_json_printer_table_vector_field(ctx, td, 2, "functions", 9, iree_instruments_DispatchFunctionDef_print_json_table);
    flatcc_json_printer_table_vector_field(ctx, td, 3, "sites", 5, iree_instruments_DispatchSiteDef_print_json_table);
}

static inline int iree_instruments_DispatchInstrumentDef_print_json_as_root(flatcc_json_printer_t *ctx, const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_json_printer_table_as_root(ctx, buf, bufsiz, fid, iree_instruments_DispatchInstrumentDef_print_json_table);
}

static int dispatch_def_print_json(flatcc_json_printer_t *ctx, const char *buf, size_t bufsiz)
{
    flatcc_json_printer_t printer;

    if (ctx == 0) {
        ctx = &printer;
        flatcc_json_printer_init(ctx, 0);
    }
    return iree_instruments_DispatchInstrumentDef_print_json_as_root(ctx, buf, bufsiz, "IDBD");
}

#include "flatcc/flatcc_epilogue.h"
#endif /* DISPATCH_DEF_JSON_PRINTER_H */
