#ifndef DISPATCH_DEF_VERIFIER_H
#define DISPATCH_DEF_VERIFIER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef DISPATCH_DEF_READER_H
#include "dispatch_def_reader.h"
#endif
#include "flatcc/flatcc_verifier.h"
#include "flatcc/flatcc_prologue.h"

static int iree_instruments_DispatchFunctionDef_verify_table(flatcc_table_verifier_descriptor_t *td);
static int iree_instruments_DispatchSiteDef_verify_table(flatcc_table_verifier_descriptor_t *td);
static int iree_instruments_DispatchInstrumentDef_verify_table(flatcc_table_verifier_descriptor_t *td);

static int iree_instruments_DispatchFunctionDef_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* name */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* target */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 2, 0) /* layout */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 3, 0) /* source */)) return ret;
    return flatcc_verify_ok;
}

static inline int iree_instruments_DispatchFunctionDef_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, iree_instruments_DispatchFunctionDef_identifier, &iree_instruments_DispatchFunctionDef_verify_table);
}

static inline int iree_instruments_DispatchFunctionDef_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, iree_instruments_DispatchFunctionDef_identifier, &iree_instruments_DispatchFunctionDef_verify_table);
}

static inline int iree_instruments_DispatchFunctionDef_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, iree_instruments_DispatchFunctionDef_type_identifier, &iree_instruments_DispatchFunctionDef_verify_table);
}

static inline int iree_instruments_DispatchFunctionDef_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, iree_instruments_DispatchFunctionDef_type_identifier, &iree_instruments_DispatchFunctionDef_verify_table);
}

static inline int iree_instruments_DispatchFunctionDef_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &iree_instruments_DispatchFunctionDef_verify_table);
}

static inline int iree_instruments_DispatchFunctionDef_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &iree_instruments_DispatchFunctionDef_verify_table);
}

static inline int iree_instruments_DispatchFunctionDef_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &iree_instruments_DispatchFunctionDef_verify_table);
}

static inline int iree_instruments_DispatchFunctionDef_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &iree_instruments_DispatchFunctionDef_verify_table);
}

static int iree_instruments_DispatchSiteDef_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 4, 4) /* function */)) return ret;
    return flatcc_verify_ok;
}

static inline int iree_instruments_DispatchSiteDef_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, iree_instruments_DispatchSiteDef_identifier, &iree_instruments_DispatchSiteDef_verify_table);
}

static inline int iree_instruments_DispatchSiteDef_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, iree_instruments_DispatchSiteDef_identifier, &iree_instruments_DispatchSiteDef_verify_table);
}

static inline int iree_instruments_DispatchSiteDef_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, iree_instruments_DispatchSiteDef_type_identifier, &iree_instruments_DispatchSiteDef_verify_table);
}

static inline int iree_instruments_DispatchSiteDef_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, iree_instruments_DispatchSiteDef_type_identifier, &iree_instruments_DispatchSiteDef_verify_table);
}

static inline int iree_instruments_DispatchSiteDef_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &iree_instruments_DispatchSiteDef_verify_table);
}

static inline int iree_instruments_DispatchSiteDef_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &iree_instruments_DispatchSiteDef_verify_table);
}

static inline int iree_instruments_DispatchSiteDef_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &iree_instruments_DispatchSiteDef_verify_table);
}

static inline int iree_instruments_DispatchSiteDef_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &iree_instruments_DispatchSiteDef_verify_table);
}

static int iree_instruments_DispatchInstrumentDef_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 4, 4) /* version */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 4, 4) /* flags */)) return ret;
    if ((ret = flatcc_verify_table_vector_field(td, 2, 0, &iree_instruments_DispatchFunctionDef_verify_table) /* functions */)) return ret;
    if ((ret = flatcc_verify_table_vector_field(td, 3, 0, &iree_instruments_DispatchSiteDef_verify_table) /* sites */)) return ret;
    return flatcc_verify_ok;
}

static inline int iree_instruments_DispatchInstrumentDef_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, iree_instruments_DispatchInstrumentDef_identifier, &iree_instruments_DispatchInstrumentDef_verify_table);
}

static inline int iree_instruments_DispatchInstrumentDef_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, iree_instruments_DispatchInstrumentDef_identifier, &iree_instruments_DispatchInstrumentDef_verify_table);
}

static inline int iree_instruments_DispatchInstrumentDef_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, iree_instruments_DispatchInstrumentDef_type_identifier, &iree_instruments_DispatchInstrumentDef_verify_table);
}

static inline int iree_instruments_DispatchInstrumentDef_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, iree_instruments_DispatchInstrumentDef_type_identifier, &iree_instruments_DispatchInstrumentDef_verify_table);
}

static inline int iree_instruments_DispatchInstrumentDef_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &iree_instruments_DispatchInstrumentDef_verify_table);
}

static inline int iree_instruments_DispatchInstrumentDef_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &iree_instruments_DispatchInstrumentDef_verify_table);
}

static inline int iree_instruments_DispatchInstrumentDef_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &iree_instruments_DispatchInstrumentDef_verify_table);
}

static inline int iree_instruments_DispatchInstrumentDef_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &iree_instruments_DispatchInstrumentDef_verify_table);
}

#include "flatcc/flatcc_epilogue.h"
#endif /* DISPATCH_DEF_VERIFIER_H */
