#ifndef DISPATCH_DEF_BUILDER_H
#define DISPATCH_DEF_BUILDER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef DISPATCH_DEF_READER_H
#include "dispatch_def_reader.h"
#endif
#ifndef FLATBUFFERS_COMMON_BUILDER_H
#include "flatbuffers_common_builder.h"
#endif
#include "flatcc/flatcc_prologue.h"
#undef flatbuffers_identifier
#define flatbuffers_identifier "IDBD"
#undef flatbuffers_extension
#define flatbuffers_extension "fb"

static const flatbuffers_voffset_t __iree_instruments_DispatchFunctionDef_required[] = { 0 };
typedef flatbuffers_ref_t iree_instruments_DispatchFunctionDef_ref_t;
static iree_instruments_DispatchFunctionDef_ref_t iree_instruments_DispatchFunctionDef_clone(flatbuffers_builder_t *B, iree_instruments_DispatchFunctionDef_table_t t);
__flatbuffers_build_table(flatbuffers_, iree_instruments_DispatchFunctionDef, 4)

static const flatbuffers_voffset_t __iree_instruments_DispatchSiteDef_required[] = { 0 };
typedef flatbuffers_ref_t iree_instruments_DispatchSiteDef_ref_t;
static iree_instruments_DispatchSiteDef_ref_t iree_instruments_DispatchSiteDef_clone(flatbuffers_builder_t *B, iree_instruments_DispatchSiteDef_table_t t);
__flatbuffers_build_table(flatbuffers_, iree_instruments_DispatchSiteDef, 1)

static const flatbuffers_voffset_t __iree_instruments_DispatchInstrumentDef_required[] = { 0 };
typedef flatbuffers_ref_t iree_instruments_DispatchInstrumentDef_ref_t;
static iree_instruments_DispatchInstrumentDef_ref_t iree_instruments_DispatchInstrumentDef_clone(flatbuffers_builder_t *B, iree_instruments_DispatchInstrumentDef_table_t t);
__flatbuffers_build_table(flatbuffers_, iree_instruments_DispatchInstrumentDef, 4)

#define __iree_instruments_DispatchFunctionDef_formal_args , flatbuffers_string_ref_t v0, flatbuffers_string_ref_t v1, flatbuffers_string_ref_t v2, flatbuffers_string_ref_t v3
#define __iree_instruments_DispatchFunctionDef_call_args , v0, v1, v2, v3
static inline iree_instruments_DispatchFunctionDef_ref_t iree_instruments_DispatchFunctionDef_create(flatbuffers_builder_t *B __iree_instruments_DispatchFunctionDef_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, iree_instruments_DispatchFunctionDef, iree_instruments_DispatchFunctionDef_file_identifier, iree_instruments_DispatchFunctionDef_type_identifier)

#define __iree_instruments_DispatchSiteDef_formal_args , uint32_t v0
#define __iree_instruments_DispatchSiteDef_call_args , v0
static inline iree_instruments_DispatchSiteDef_ref_t iree_instruments_DispatchSiteDef_create(flatbuffers_builder_t *B __iree_instruments_DispatchSiteDef_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, iree_instruments_DispatchSiteDef, iree_instruments_DispatchSiteDef_file_identifier, iree_instruments_DispatchSiteDef_type_identifier)

#define __iree_instruments_DispatchInstrumentDef_formal_args , uint32_t v0, uint32_t v1, iree_instruments_DispatchFunctionDef_vec_ref_t v2, iree_instruments_DispatchSiteDef_vec_ref_t v3
#define __iree_instruments_DispatchInstrumentDef_call_args , v0, v1, v2, v3
static inline iree_instruments_DispatchInstrumentDef_ref_t iree_instruments_DispatchInstrumentDef_create(flatbuffers_builder_t *B __iree_instruments_DispatchInstrumentDef_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, iree_instruments_DispatchInstrumentDef, iree_instruments_DispatchInstrumentDef_file_identifier, iree_instruments_DispatchInstrumentDef_type_identifier)

__flatbuffers_build_string_field(0, flatbuffers_, iree_instruments_DispatchFunctionDef_name, iree_instruments_DispatchFunctionDef)
__flatbuffers_build_string_field(1, flatbuffers_, iree_instruments_DispatchFunctionDef_target, iree_instruments_DispatchFunctionDef)
__flatbuffers_build_string_field(2, flatbuffers_, iree_instruments_DispatchFunctionDef_layout, iree_instruments_DispatchFunctionDef)
__flatbuffers_build_string_field(3, flatbuffers_, iree_instruments_DispatchFunctionDef_source, iree_instruments_DispatchFunctionDef)

static inline iree_instruments_DispatchFunctionDef_ref_t iree_instruments_DispatchFunctionDef_create(flatbuffers_builder_t *B __iree_instruments_DispatchFunctionDef_formal_args)
{
    if (iree_instruments_DispatchFunctionDef_start(B)
        || iree_instruments_DispatchFunctionDef_name_add(B, v0)
        || iree_instruments_DispatchFunctionDef_target_add(B, v1)
        || iree_instruments_DispatchFunctionDef_layout_add(B, v2)
        || iree_instruments_DispatchFunctionDef_source_add(B, v3)) {
        return 0;
    }
    return iree_instruments_DispatchFunctionDef_end(B);
}

static iree_instruments_DispatchFunctionDef_ref_t iree_instruments_DispatchFunctionDef_clone(flatbuffers_builder_t *B, iree_instruments_DispatchFunctionDef_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (iree_instruments_DispatchFunctionDef_start(B)
        || iree_instruments_DispatchFunctionDef_name_pick(B, t)
        || iree_instruments_DispatchFunctionDef_target_pick(B, t)
        || iree_instruments_DispatchFunctionDef_layout_pick(B, t)
        || iree_instruments_DispatchFunctionDef_source_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, iree_instruments_DispatchFunctionDef_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, iree_instruments_DispatchSiteDef_function, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), iree_instruments_DispatchSiteDef)

static inline iree_instruments_DispatchSiteDef_ref_t iree_instruments_DispatchSiteDef_create(flatbuffers_builder_t *B __iree_instruments_DispatchSiteDef_formal_args)
{
    if (iree_instruments_DispatchSiteDef_start(B)
        || iree_instruments_DispatchSiteDef_function_add(B, v0)) {
        return 0;
    }
    return iree_instruments_DispatchSiteDef_end(B);
}

static iree_instruments_DispatchSiteDef_ref_t iree_instruments_DispatchSiteDef_clone(flatbuffers_builder_t *B, iree_instruments_DispatchSiteDef_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (iree_instruments_DispatchSiteDef_start(B)
        || iree_instruments_DispatchSiteDef_function_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, iree_instruments_DispatchSiteDef_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, iree_instruments_DispatchInstrumentDef_version, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), iree_instruments_DispatchInstrumentDef)
__flatbuffers_build_scalar_field(1, flatbuffers_, iree_instruments_DispatchInstrumentDef_flags, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), iree_instruments_DispatchInstrumentDef)
__flatbuffers_build_table_vector_field(2, flatbuffers_, iree_instruments_DispatchInstrumentDef_functions, iree_instruments_DispatchFunctionDef, iree_instruments_DispatchInstrumentDef)
__flatbuffers_build_table_vector_field(3, flatbuffers_, iree_instruments_DispatchInstrumentDef_sites, iree_instruments_DispatchSiteDef, iree_instruments_DispatchInstrumentDef)

static inline iree_instruments_DispatchInstrumentDef_ref_t iree_instruments_DispatchInstrumentDef_create(flatbuffers_builder_t *B __iree_instruments_DispatchInstrumentDef_formal_args)
{
    if (iree_instruments_DispatchInstrumentDef_start(B)
        || iree_instruments_DispatchInstrumentDef_version_add(B, v0)
        || iree_instruments_DispatchInstrumentDef_flags_add(B, v1)
        || iree_instruments_DispatchInstrumentDef_functions_add(B, v2)
        || iree_instruments_DispatchInstrumentDef_sites_add(B, v3)) {
        return 0;
    }
    return iree_instruments_DispatchInstrumentDef_end(B);
}

static iree_instruments_DispatchInstrumentDef_ref_t iree_instruments_DispatchInstrumentDef_clone(flatbuffers_builder_t *B, iree_instruments_DispatchInstrumentDef_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (iree_instruments_DispatchInstrumentDef_start(B)
        || iree_instruments_DispatchInstrumentDef_version_pick(B, t)
        || iree_instruments_DispatchInstrumentDef_flags_pick(B, t)
        || iree_instruments_DispatchInstrumentDef_functions_pick(B, t)
        || iree_instruments_DispatchInstrumentDef_sites_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, iree_instruments_DispatchInstrumentDef_end(B));
}

#include "flatcc/flatcc_epilogue.h"
#endif /* DISPATCH_DEF_BUILDER_H */
