# CMake generated Testfile for 
# Source directory: /home/chlee/iree/tests/e2e/vulkan_specific
# Build directory: /home/chlee/iree-build-riscv/tests/e2e/vulkan_specific
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[iree/tests/e2e/vulkan_specific/check_vulkan-spirv_vulkan_f16_add_f16.mlir]=] "/home/chlee/iree/build_tools/cmake/run_riscv_test.sh" "/home/chlee/iree-build-riscv/tools/iree-check-module" "--module=check_vulkan-spirv_vulkan_f16_add_f16.mlir_module.vmfb" "--device=vulkan")
set_tests_properties([=[iree/tests/e2e/vulkan_specific/check_vulkan-spirv_vulkan_f16_add_f16.mlir]=] PROPERTIES  ENVIRONMENT "TEST_TMPDIR=/home/chlee/iree-build-riscv/test_tmpdir/iree/tests/e2e/vulkan_specific/check_vulkan-spirv_vulkan_f16_add_f16.mlir_test_tmpdir;IREE_BINARY_DIR=/home/chlee/iree-build-riscv;IREE_DYLIB_EXT=.so;IREE_VULKAN_DISABLE=1;IREE_METAL_DISABLE=1" LABELS "test-type=check-test;manual;notap;vulkan_uses_vk_khr_16bit_storage;vulkan_uses_vk_khr_shader_float16_int8;driver=vulkan;iree/tests/e2e/vulkan_specific" REQUIRED_FILES "check_vulkan-spirv_vulkan_f16_add_f16.mlir_module.vmfb" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/chlee/iree/build_tools/cmake/iree_native_test.cmake;131;add_test;/home/chlee/iree/build_tools/cmake/iree_check_test.cmake;196;iree_native_test;/home/chlee/iree/build_tools/cmake/iree_check_test.cmake;269;iree_check_test;/home/chlee/iree/tests/e2e/vulkan_specific/CMakeLists.txt;13;iree_check_single_backend_test_suite;/home/chlee/iree/tests/e2e/vulkan_specific/CMakeLists.txt;0;")
add_test([=[iree/tests/e2e/vulkan_specific/check_vulkan-spirv_vulkan_f16_dot_f16.mlir]=] "/home/chlee/iree/build_tools/cmake/run_riscv_test.sh" "/home/chlee/iree-build-riscv/tools/iree-check-module" "--module=check_vulkan-spirv_vulkan_f16_dot_f16.mlir_module.vmfb" "--device=vulkan")
set_tests_properties([=[iree/tests/e2e/vulkan_specific/check_vulkan-spirv_vulkan_f16_dot_f16.mlir]=] PROPERTIES  ENVIRONMENT "TEST_TMPDIR=/home/chlee/iree-build-riscv/test_tmpdir/iree/tests/e2e/vulkan_specific/check_vulkan-spirv_vulkan_f16_dot_f16.mlir_test_tmpdir;IREE_BINARY_DIR=/home/chlee/iree-build-riscv;IREE_DYLIB_EXT=.so;IREE_VULKAN_DISABLE=1;IREE_METAL_DISABLE=1" LABELS "test-type=check-test;manual;notap;vulkan_uses_vk_khr_16bit_storage;vulkan_uses_vk_khr_shader_float16_int8;driver=vulkan;iree/tests/e2e/vulkan_specific" REQUIRED_FILES "check_vulkan-spirv_vulkan_f16_dot_f16.mlir_module.vmfb" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/chlee/iree/build_tools/cmake/iree_native_test.cmake;131;add_test;/home/chlee/iree/build_tools/cmake/iree_check_test.cmake;196;iree_native_test;/home/chlee/iree/build_tools/cmake/iree_check_test.cmake;269;iree_check_test;/home/chlee/iree/tests/e2e/vulkan_specific/CMakeLists.txt;13;iree_check_single_backend_test_suite;/home/chlee/iree/tests/e2e/vulkan_specific/CMakeLists.txt;0;")
add_test([=[iree/tests/e2e/vulkan_specific/check_vulkan-spirv_vulkan_conv_conv.mlir]=] "/home/chlee/iree/build_tools/cmake/run_riscv_test.sh" "/home/chlee/iree-build-riscv/tools/iree-check-module" "--module=check_vulkan-spirv_vulkan_conv_conv.mlir_module.vmfb" "--device=vulkan")
set_tests_properties([=[iree/tests/e2e/vulkan_specific/check_vulkan-spirv_vulkan_conv_conv.mlir]=] PROPERTIES  ENVIRONMENT "TEST_TMPDIR=/home/chlee/iree-build-riscv/test_tmpdir/iree/tests/e2e/vulkan_specific/check_vulkan-spirv_vulkan_conv_conv.mlir_test_tmpdir;IREE_BINARY_DIR=/home/chlee/iree-build-riscv;IREE_DYLIB_EXT=.so;IREE_VULKAN_DISABLE=1;IREE_METAL_DISABLE=1" LABELS "test-type=check-test;driver=vulkan;iree/tests/e2e/vulkan_specific" REQUIRED_FILES "check_vulkan-spirv_vulkan_conv_conv.mlir_module.vmfb" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/chlee/iree/build_tools/cmake/iree_native_test.cmake;131;add_test;/home/chlee/iree/build_tools/cmake/iree_check_test.cmake;196;iree_native_test;/home/chlee/iree/build_tools/cmake/iree_check_test.cmake;269;iree_check_test;/home/chlee/iree/tests/e2e/vulkan_specific/CMakeLists.txt;33;iree_check_single_backend_test_suite;/home/chlee/iree/tests/e2e/vulkan_specific/CMakeLists.txt;0;")
add_test([=[iree/tests/e2e/vulkan_specific/check_vulkan-spirv_vulkan_i64_emulation_add_i64.mlir]=] "/home/chlee/iree/build_tools/cmake/run_riscv_test.sh" "/home/chlee/iree-build-riscv/tools/iree-check-module" "--module=check_vulkan-spirv_vulkan_i64_emulation_add_i64.mlir_module.vmfb" "--device=vulkan")
set_tests_properties([=[iree/tests/e2e/vulkan_specific/check_vulkan-spirv_vulkan_i64_emulation_add_i64.mlir]=] PROPERTIES  ENVIRONMENT "TEST_TMPDIR=/home/chlee/iree-build-riscv/test_tmpdir/iree/tests/e2e/vulkan_specific/check_vulkan-spirv_vulkan_i64_emulation_add_i64.mlir_test_tmpdir;IREE_BINARY_DIR=/home/chlee/iree-build-riscv;IREE_DYLIB_EXT=.so;IREE_VULKAN_DISABLE=1;IREE_METAL_DISABLE=1" LABELS "test-type=check-test;manual;notap;vulkan_uses_shader_int64;driver=vulkan;iree/tests/e2e/vulkan_specific" REQUIRED_FILES "check_vulkan-spirv_vulkan_i64_emulation_add_i64.mlir_module.vmfb" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/chlee/iree/build_tools/cmake/iree_native_test.cmake;131;add_test;/home/chlee/iree/build_tools/cmake/iree_check_test.cmake;196;iree_native_test;/home/chlee/iree/build_tools/cmake/iree_check_test.cmake;269;iree_check_test;/home/chlee/iree/tests/e2e/vulkan_specific/CMakeLists.txt;47;iree_check_single_backend_test_suite;/home/chlee/iree/tests/e2e/vulkan_specific/CMakeLists.txt;0;")
add_test([=[iree/tests/e2e/vulkan_specific/check_vulkan-spirv_vulkan_i64_emulation_mul_i64.mlir]=] "/home/chlee/iree/build_tools/cmake/run_riscv_test.sh" "/home/chlee/iree-build-riscv/tools/iree-check-module" "--module=check_vulkan-spirv_vulkan_i64_emulation_mul_i64.mlir_module.vmfb" "--device=vulkan")
set_tests_properties([=[iree/tests/e2e/vulkan_specific/check_vulkan-spirv_vulkan_i64_emulation_mul_i64.mlir]=] PROPERTIES  ENVIRONMENT "TEST_TMPDIR=/home/chlee/iree-build-riscv/test_tmpdir/iree/tests/e2e/vulkan_specific/check_vulkan-spirv_vulkan_i64_emulation_mul_i64.mlir_test_tmpdir;IREE_BINARY_DIR=/home/chlee/iree-build-riscv;IREE_DYLIB_EXT=.so;IREE_VULKAN_DISABLE=1;IREE_METAL_DISABLE=1" LABELS "test-type=check-test;manual;notap;vulkan_uses_shader_int64;driver=vulkan;iree/tests/e2e/vulkan_specific" REQUIRED_FILES "check_vulkan-spirv_vulkan_i64_emulation_mul_i64.mlir_module.vmfb" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/chlee/iree/build_tools/cmake/iree_native_test.cmake;131;add_test;/home/chlee/iree/build_tools/cmake/iree_check_test.cmake;196;iree_native_test;/home/chlee/iree/build_tools/cmake/iree_check_test.cmake;269;iree_check_test;/home/chlee/iree/tests/e2e/vulkan_specific/CMakeLists.txt;47;iree_check_single_backend_test_suite;/home/chlee/iree/tests/e2e/vulkan_specific/CMakeLists.txt;0;")
