# CMake generated Testfile for 
# Source directory: /home/chlee/iree/tests/e2e/stablehlo_models
# Build directory: /home/chlee/iree-build-riscv/tests/e2e/stablehlo_models
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[iree/tests/e2e/stablehlo_models/mnist_fake_weights_llvm_cpu_static_bytecode_test]=] "/home/chlee/iree/build_tools/cmake/run_riscv_test.sh" "/home/chlee/iree-build-riscv/tests/e2e/stablehlo_models/mnist_fake_weights_llvm_cpu_static_bytecode_test_run" "--device=local-sync")
set_tests_properties([=[iree/tests/e2e/stablehlo_models/mnist_fake_weights_llvm_cpu_static_bytecode_test]=] PROPERTIES  ENVIRONMENT "TEST_TMPDIR=/home/chlee/iree-build-riscv/test_tmpdir/iree/tests/e2e/stablehlo_models/mnist_fake_weights_llvm_cpu_static_bytecode_test_test_tmpdir;IREE_BINARY_DIR=/home/chlee/iree-build-riscv;IREE_DYLIB_EXT=.so;IREE_VULKAN_DISABLE=1;IREE_METAL_DISABLE=1" LABELS "driver=local-sync;iree/tests/e2e/stablehlo_models" REQUIRED_FILES "" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/chlee/iree/build_tools/cmake/iree_native_test.cmake;131;add_test;/home/chlee/iree/build_tools/cmake/iree_static_linker_test.cmake;263;iree_native_test;/home/chlee/iree/tests/e2e/stablehlo_models/CMakeLists.txt;39;iree_static_linker_test;/home/chlee/iree/tests/e2e/stablehlo_models/CMakeLists.txt;0;")
add_test([=[iree/tests/e2e/stablehlo_models/mnist_fake_weights_llvm_cpu_static_c_test]=] "/home/chlee/iree/build_tools/cmake/run_riscv_test.sh" "/home/chlee/iree-build-riscv/tests/e2e/stablehlo_models/mnist_fake_weights_llvm_cpu_static_c_test_run" "--device=local-sync")
set_tests_properties([=[iree/tests/e2e/stablehlo_models/mnist_fake_weights_llvm_cpu_static_c_test]=] PROPERTIES  ENVIRONMENT "TEST_TMPDIR=/home/chlee/iree-build-riscv/test_tmpdir/iree/tests/e2e/stablehlo_models/mnist_fake_weights_llvm_cpu_static_c_test_test_tmpdir;IREE_BINARY_DIR=/home/chlee/iree-build-riscv;IREE_DYLIB_EXT=.so;IREE_VULKAN_DISABLE=1;IREE_METAL_DISABLE=1" LABELS "driver=local-sync;iree/tests/e2e/stablehlo_models" REQUIRED_FILES "" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/chlee/iree/build_tools/cmake/iree_native_test.cmake;131;add_test;/home/chlee/iree/build_tools/cmake/iree_static_linker_test.cmake;263;iree_native_test;/home/chlee/iree/tests/e2e/stablehlo_models/CMakeLists.txt;54;iree_static_linker_test;/home/chlee/iree/tests/e2e/stablehlo_models/CMakeLists.txt;0;")
add_test([=[iree/tests/e2e/stablehlo_models/simple_mul_llvm_cpu_static_bytecode_test]=] "/home/chlee/iree/build_tools/cmake/run_riscv_test.sh" "/home/chlee/iree-build-riscv/tests/e2e/stablehlo_models/simple_mul_llvm_cpu_static_bytecode_test_run" "--device=local-sync")
set_tests_properties([=[iree/tests/e2e/stablehlo_models/simple_mul_llvm_cpu_static_bytecode_test]=] PROPERTIES  ENVIRONMENT "TEST_TMPDIR=/home/chlee/iree-build-riscv/test_tmpdir/iree/tests/e2e/stablehlo_models/simple_mul_llvm_cpu_static_bytecode_test_test_tmpdir;IREE_BINARY_DIR=/home/chlee/iree-build-riscv;IREE_DYLIB_EXT=.so;IREE_VULKAN_DISABLE=1;IREE_METAL_DISABLE=1" LABELS "driver=local-sync;iree/tests/e2e/stablehlo_models" REQUIRED_FILES "" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/chlee/iree/build_tools/cmake/iree_native_test.cmake;131;add_test;/home/chlee/iree/build_tools/cmake/iree_static_linker_test.cmake;263;iree_native_test;/home/chlee/iree/tests/e2e/stablehlo_models/CMakeLists.txt;71;iree_static_linker_test;/home/chlee/iree/tests/e2e/stablehlo_models/CMakeLists.txt;0;")
add_test([=[iree/tests/e2e/stablehlo_models/simple_mul_llvm_cpu_static_c_test]=] "/home/chlee/iree/build_tools/cmake/run_riscv_test.sh" "/home/chlee/iree-build-riscv/tests/e2e/stablehlo_models/simple_mul_llvm_cpu_static_c_test_run" "--device=local-sync")
set_tests_properties([=[iree/tests/e2e/stablehlo_models/simple_mul_llvm_cpu_static_c_test]=] PROPERTIES  ENVIRONMENT "TEST_TMPDIR=/home/chlee/iree-build-riscv/test_tmpdir/iree/tests/e2e/stablehlo_models/simple_mul_llvm_cpu_static_c_test_test_tmpdir;IREE_BINARY_DIR=/home/chlee/iree-build-riscv;IREE_DYLIB_EXT=.so;IREE_VULKAN_DISABLE=1;IREE_METAL_DISABLE=1" LABELS "driver=local-sync;iree/tests/e2e/stablehlo_models" REQUIRED_FILES "" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/chlee/iree/build_tools/cmake/iree_native_test.cmake;131;add_test;/home/chlee/iree/build_tools/cmake/iree_static_linker_test.cmake;263;iree_native_test;/home/chlee/iree/tests/e2e/stablehlo_models/CMakeLists.txt;84;iree_static_linker_test;/home/chlee/iree/tests/e2e/stablehlo_models/CMakeLists.txt;0;")
subdirs("mnist_train_test")
