# CMake generated Testfile for 
# Source directory: /home/chlee/iree/runtime/src/iree/builtins/ukernel/tools
# Build directory: /home/chlee/iree-build-riscv/runtime/src/iree/builtins/ukernel/tools
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[iree/builtins/ukernel/tools/util_test]=] "/home/chlee/iree/build_tools/cmake/run_riscv_test.sh" "/home/chlee/iree-build-riscv/runtime/src/iree/builtins/ukernel/tools/util_test")
set_tests_properties([=[iree/builtins/ukernel/tools/util_test]=] PROPERTIES  ENVIRONMENT "TEST_TMPDIR=/home/chlee/iree-build-riscv/test_tmpdir/iree/builtins/ukernel/tools/util_test_test_tmpdir;IREE_BINARY_DIR=/home/chlee/iree-build-riscv;IREE_DYLIB_EXT=.so;IREE_VULKAN_DISABLE=1;IREE_METAL_DISABLE=1" LABELS "iree/builtins/ukernel/tools" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/chlee/iree/build_tools/cmake/iree_cc_test.cmake;170;add_test;/home/chlee/iree/runtime/src/iree/builtins/ukernel/tools/CMakeLists.txt;45;iree_cc_test;/home/chlee/iree/runtime/src/iree/builtins/ukernel/tools/CMakeLists.txt;0;")
add_test([=[iree/builtins/ukernel/tools/mmt4d_benchmark_test]=] "/home/chlee/iree/build_tools/cmake/run_riscv_test.sh" "/home/chlee/iree-build-riscv/runtime/src/iree/builtins/ukernel/tools/mmt4d_benchmark" "--benchmark_min_time=0")
set_tests_properties([=[iree/builtins/ukernel/tools/mmt4d_benchmark_test]=] PROPERTIES  ENVIRONMENT "TEST_TMPDIR=/home/chlee/iree-build-riscv/test_tmpdir/iree/builtins/ukernel/tools/mmt4d_benchmark_test_test_tmpdir;IREE_BINARY_DIR=/home/chlee/iree-build-riscv;IREE_DYLIB_EXT=.so;IREE_VULKAN_DISABLE=1;IREE_METAL_DISABLE=1" LABELS "iree/builtins/ukernel/tools" REQUIRED_FILES "" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/chlee/iree/build_tools/cmake/iree_native_test.cmake;131;add_test;/home/chlee/iree/build_tools/cmake/iree_cc_binary_benchmark.cmake;72;iree_native_test;/home/chlee/iree/runtime/src/iree/builtins/ukernel/tools/CMakeLists.txt;89;iree_cc_binary_benchmark;/home/chlee/iree/runtime/src/iree/builtins/ukernel/tools/CMakeLists.txt;0;")
add_test([=[iree/builtins/ukernel/tools/mmt4d_test]=] "/home/chlee/iree/build_tools/cmake/run_riscv_test.sh" "/home/chlee/iree-build-riscv/runtime/src/iree/builtins/ukernel/tools/mmt4d_test")
set_tests_properties([=[iree/builtins/ukernel/tools/mmt4d_test]=] PROPERTIES  ENVIRONMENT "TEST_TMPDIR=/home/chlee/iree-build-riscv/test_tmpdir/iree/builtins/ukernel/tools/mmt4d_test_test_tmpdir;IREE_BINARY_DIR=/home/chlee/iree-build-riscv;IREE_DYLIB_EXT=.so;IREE_VULKAN_DISABLE=1;IREE_METAL_DISABLE=1" LABELS "iree/builtins/ukernel/tools" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/chlee/iree/build_tools/cmake/iree_cc_test.cmake;170;add_test;/home/chlee/iree/runtime/src/iree/builtins/ukernel/tools/CMakeLists.txt;105;iree_cc_test;/home/chlee/iree/runtime/src/iree/builtins/ukernel/tools/CMakeLists.txt;0;")
add_test([=[iree/builtins/ukernel/tools/pack_benchmark_test]=] "/home/chlee/iree/build_tools/cmake/run_riscv_test.sh" "/home/chlee/iree-build-riscv/runtime/src/iree/builtins/ukernel/tools/pack_benchmark" "--benchmark_min_time=0")
set_tests_properties([=[iree/builtins/ukernel/tools/pack_benchmark_test]=] PROPERTIES  ENVIRONMENT "TEST_TMPDIR=/home/chlee/iree-build-riscv/test_tmpdir/iree/builtins/ukernel/tools/pack_benchmark_test_test_tmpdir;IREE_BINARY_DIR=/home/chlee/iree-build-riscv;IREE_DYLIB_EXT=.so;IREE_VULKAN_DISABLE=1;IREE_METAL_DISABLE=1" LABELS "iree/builtins/ukernel/tools" REQUIRED_FILES "" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/chlee/iree/build_tools/cmake/iree_native_test.cmake;131;add_test;/home/chlee/iree/build_tools/cmake/iree_cc_binary_benchmark.cmake;72;iree_native_test;/home/chlee/iree/runtime/src/iree/builtins/ukernel/tools/CMakeLists.txt;120;iree_cc_binary_benchmark;/home/chlee/iree/runtime/src/iree/builtins/ukernel/tools/CMakeLists.txt;0;")
add_test([=[iree/builtins/ukernel/tools/pack_test]=] "/home/chlee/iree/build_tools/cmake/run_riscv_test.sh" "/home/chlee/iree-build-riscv/runtime/src/iree/builtins/ukernel/tools/pack_test")
set_tests_properties([=[iree/builtins/ukernel/tools/pack_test]=] PROPERTIES  ENVIRONMENT "TEST_TMPDIR=/home/chlee/iree-build-riscv/test_tmpdir/iree/builtins/ukernel/tools/pack_test_test_tmpdir;IREE_BINARY_DIR=/home/chlee/iree-build-riscv;IREE_DYLIB_EXT=.so;IREE_VULKAN_DISABLE=1;IREE_METAL_DISABLE=1" LABELS "iree/builtins/ukernel/tools" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/chlee/iree/build_tools/cmake/iree_cc_test.cmake;170;add_test;/home/chlee/iree/runtime/src/iree/builtins/ukernel/tools/CMakeLists.txt;137;iree_cc_test;/home/chlee/iree/runtime/src/iree/builtins/ukernel/tools/CMakeLists.txt;0;")
add_test([=[iree/builtins/ukernel/tools/unpack_benchmark_test]=] "/home/chlee/iree/build_tools/cmake/run_riscv_test.sh" "/home/chlee/iree-build-riscv/runtime/src/iree/builtins/ukernel/tools/unpack_benchmark" "--benchmark_min_time=0")
set_tests_properties([=[iree/builtins/ukernel/tools/unpack_benchmark_test]=] PROPERTIES  ENVIRONMENT "TEST_TMPDIR=/home/chlee/iree-build-riscv/test_tmpdir/iree/builtins/ukernel/tools/unpack_benchmark_test_test_tmpdir;IREE_BINARY_DIR=/home/chlee/iree-build-riscv;IREE_DYLIB_EXT=.so;IREE_VULKAN_DISABLE=1;IREE_METAL_DISABLE=1" LABELS "iree/builtins/ukernel/tools" REQUIRED_FILES "" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/chlee/iree/build_tools/cmake/iree_native_test.cmake;131;add_test;/home/chlee/iree/build_tools/cmake/iree_cc_binary_benchmark.cmake;72;iree_native_test;/home/chlee/iree/runtime/src/iree/builtins/ukernel/tools/CMakeLists.txt;151;iree_cc_binary_benchmark;/home/chlee/iree/runtime/src/iree/builtins/ukernel/tools/CMakeLists.txt;0;")
add_test([=[iree/builtins/ukernel/tools/unpack_test]=] "/home/chlee/iree/build_tools/cmake/run_riscv_test.sh" "/home/chlee/iree-build-riscv/runtime/src/iree/builtins/ukernel/tools/unpack_test")
set_tests_properties([=[iree/builtins/ukernel/tools/unpack_test]=] PROPERTIES  ENVIRONMENT "TEST_TMPDIR=/home/chlee/iree-build-riscv/test_tmpdir/iree/builtins/ukernel/tools/unpack_test_test_tmpdir;IREE_BINARY_DIR=/home/chlee/iree-build-riscv;IREE_DYLIB_EXT=.so;IREE_VULKAN_DISABLE=1;IREE_METAL_DISABLE=1" LABELS "iree/builtins/ukernel/tools" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/chlee/iree/build_tools/cmake/iree_cc_test.cmake;170;add_test;/home/chlee/iree/runtime/src/iree/builtins/ukernel/tools/CMakeLists.txt;168;iree_cc_test;/home/chlee/iree/runtime/src/iree/builtins/ukernel/tools/CMakeLists.txt;0;")
add_test([=[iree/builtins/ukernel/tools/e2e_matmul_benchmark_test]=] "/home/chlee/iree/build_tools/cmake/run_riscv_test.sh" "/home/chlee/iree-build-riscv/runtime/src/iree/builtins/ukernel/tools/e2e_matmul_benchmark" "--benchmark_min_time=0")
set_tests_properties([=[iree/builtins/ukernel/tools/e2e_matmul_benchmark_test]=] PROPERTIES  ENVIRONMENT "TEST_TMPDIR=/home/chlee/iree-build-riscv/test_tmpdir/iree/builtins/ukernel/tools/e2e_matmul_benchmark_test_test_tmpdir;IREE_BINARY_DIR=/home/chlee/iree-build-riscv;IREE_DYLIB_EXT=.so;IREE_VULKAN_DISABLE=1;IREE_METAL_DISABLE=1" LABELS "iree/builtins/ukernel/tools" REQUIRED_FILES "" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/chlee/iree/build_tools/cmake/iree_native_test.cmake;131;add_test;/home/chlee/iree/build_tools/cmake/iree_cc_binary_benchmark.cmake;72;iree_native_test;/home/chlee/iree/runtime/src/iree/builtins/ukernel/tools/CMakeLists.txt;183;iree_cc_binary_benchmark;/home/chlee/iree/runtime/src/iree/builtins/ukernel/tools/CMakeLists.txt;0;")
