#ifndef EXECUTABLE_DEBUG_INFO_BUILDER_H
#define EXECUTABLE_DEBUG_INFO_BUILDER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef EXECUTABLE_DEBUG_INFO_READER_H
#include "executable_debug_info_reader.h"
#endif
#ifndef FLATBUFFERS_COMMON_BUILDER_H
#include "flatbuffers_common_builder.h"
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension "bin"
#endif

static const flatbuffers_voffset_t __iree_hal_debug_FileLineLocDef_required[] = { 0 };
typedef flatbuffers_ref_t iree_hal_debug_FileLineLocDef_ref_t;
static iree_hal_debug_FileLineLocDef_ref_t iree_hal_debug_FileLineLocDef_clone(flatbuffers_builder_t *B, iree_hal_debug_FileLineLocDef_table_t t);
__flatbuffers_build_table(flatbuffers_, iree_hal_debug_FileLineLocDef, 2)

static const flatbuffers_voffset_t __iree_hal_debug_StageLocationDef_required[] = { 0 };
typedef flatbuffers_ref_t iree_hal_debug_StageLocationDef_ref_t;
static iree_hal_debug_StageLocationDef_ref_t iree_hal_debug_StageLocationDef_clone(flatbuffers_builder_t *B, iree_hal_debug_StageLocationDef_table_t t);
__flatbuffers_build_table(flatbuffers_, iree_hal_debug_StageLocationDef, 2)

static const flatbuffers_voffset_t __iree_hal_debug_ExportDef_required[] = { 0 };
typedef flatbuffers_ref_t iree_hal_debug_ExportDef_ref_t;
static iree_hal_debug_ExportDef_ref_t iree_hal_debug_ExportDef_clone(flatbuffers_builder_t *B, iree_hal_debug_ExportDef_table_t t);
__flatbuffers_build_table(flatbuffers_, iree_hal_debug_ExportDef, 3)

static const flatbuffers_voffset_t __iree_hal_debug_SourceFileDef_required[] = { 0 };
typedef flatbuffers_ref_t iree_hal_debug_SourceFileDef_ref_t;
static iree_hal_debug_SourceFileDef_ref_t iree_hal_debug_SourceFileDef_clone(flatbuffers_builder_t *B, iree_hal_debug_SourceFileDef_table_t t);
__flatbuffers_build_table(flatbuffers_, iree_hal_debug_SourceFileDef, 2)

#define __iree_hal_debug_FileLineLocDef_formal_args , flatbuffers_string_ref_t v0, int32_t v1
#define __iree_hal_debug_FileLineLocDef_call_args , v0, v1
static inline iree_hal_debug_FileLineLocDef_ref_t iree_hal_debug_FileLineLocDef_create(flatbuffers_builder_t *B __iree_hal_debug_FileLineLocDef_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, iree_hal_debug_FileLineLocDef, iree_hal_debug_FileLineLocDef_file_identifier, iree_hal_debug_FileLineLocDef_type_identifier)

#define __iree_hal_debug_StageLocationDef_formal_args , flatbuffers_string_ref_t v0, iree_hal_debug_FileLineLocDef_ref_t v1
#define __iree_hal_debug_StageLocationDef_call_args , v0, v1
static inline iree_hal_debug_StageLocationDef_ref_t iree_hal_debug_StageLocationDef_create(flatbuffers_builder_t *B __iree_hal_debug_StageLocationDef_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, iree_hal_debug_StageLocationDef, iree_hal_debug_StageLocationDef_file_identifier, iree_hal_debug_StageLocationDef_type_identifier)

#define __iree_hal_debug_ExportDef_formal_args , flatbuffers_string_ref_t v0, iree_hal_debug_FileLineLocDef_ref_t v1, iree_hal_debug_StageLocationDef_vec_ref_t v2
#define __iree_hal_debug_ExportDef_call_args , v0, v1, v2
static inline iree_hal_debug_ExportDef_ref_t iree_hal_debug_ExportDef_create(flatbuffers_builder_t *B __iree_hal_debug_ExportDef_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, iree_hal_debug_ExportDef, iree_hal_debug_ExportDef_file_identifier, iree_hal_debug_ExportDef_type_identifier)

#define __iree_hal_debug_SourceFileDef_formal_args , flatbuffers_string_ref_t v0, flatbuffers_uint8_vec_ref_t v1
#define __iree_hal_debug_SourceFileDef_call_args , v0, v1
static inline iree_hal_debug_SourceFileDef_ref_t iree_hal_debug_SourceFileDef_create(flatbuffers_builder_t *B __iree_hal_debug_SourceFileDef_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, iree_hal_debug_SourceFileDef, iree_hal_debug_SourceFileDef_file_identifier, iree_hal_debug_SourceFileDef_type_identifier)

__flatbuffers_build_string_field(0, flatbuffers_, iree_hal_debug_FileLineLocDef_filename, iree_hal_debug_FileLineLocDef)
__flatbuffers_build_scalar_field(1, flatbuffers_, iree_hal_debug_FileLineLocDef_line, flatbuffers_int32, int32_t, 4, 4, INT32_C(0), iree_hal_debug_FileLineLocDef)

static inline iree_hal_debug_FileLineLocDef_ref_t iree_hal_debug_FileLineLocDef_create(flatbuffers_builder_t *B __iree_hal_debug_FileLineLocDef_formal_args)
{
    if (iree_hal_debug_FileLineLocDef_start(B)
        || iree_hal_debug_FileLineLocDef_filename_add(B, v0)
        || iree_hal_debug_FileLineLocDef_line_add(B, v1)) {
        return 0;
    }
    return iree_hal_debug_FileLineLocDef_end(B);
}

static iree_hal_debug_FileLineLocDef_ref_t iree_hal_debug_FileLineLocDef_clone(flatbuffers_builder_t *B, iree_hal_debug_FileLineLocDef_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (iree_hal_debug_FileLineLocDef_start(B)
        || iree_hal_debug_FileLineLocDef_filename_pick(B, t)
        || iree_hal_debug_FileLineLocDef_line_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, iree_hal_debug_FileLineLocDef_end(B));
}

__flatbuffers_build_string_field(0, flatbuffers_, iree_hal_debug_StageLocationDef_stage, iree_hal_debug_StageLocationDef)
__flatbuffers_build_table_field(1, flatbuffers_, iree_hal_debug_StageLocationDef_location, iree_hal_debug_FileLineLocDef, iree_hal_debug_StageLocationDef)

static inline iree_hal_debug_StageLocationDef_ref_t iree_hal_debug_StageLocationDef_create(flatbuffers_builder_t *B __iree_hal_debug_StageLocationDef_formal_args)
{
    if (iree_hal_debug_StageLocationDef_start(B)
        || iree_hal_debug_StageLocationDef_stage_add(B, v0)
        || iree_hal_debug_StageLocationDef_location_add(B, v1)) {
        return 0;
    }
    return iree_hal_debug_StageLocationDef_end(B);
}

static iree_hal_debug_StageLocationDef_ref_t iree_hal_debug_StageLocationDef_clone(flatbuffers_builder_t *B, iree_hal_debug_StageLocationDef_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (iree_hal_debug_StageLocationDef_start(B)
        || iree_hal_debug_StageLocationDef_stage_pick(B, t)
        || iree_hal_debug_StageLocationDef_location_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, iree_hal_debug_StageLocationDef_end(B));
}

__flatbuffers_build_string_field(0, flatbuffers_, iree_hal_debug_ExportDef_name, iree_hal_debug_ExportDef)
__flatbuffers_build_table_field(1, flatbuffers_, iree_hal_debug_ExportDef_location, iree_hal_debug_FileLineLocDef, iree_hal_debug_ExportDef)
__flatbuffers_build_table_vector_field(2, flatbuffers_, iree_hal_debug_ExportDef_stage_locations, iree_hal_debug_StageLocationDef, iree_hal_debug_ExportDef)

static inline iree_hal_debug_ExportDef_ref_t iree_hal_debug_ExportDef_create(flatbuffers_builder_t *B __iree_hal_debug_ExportDef_formal_args)
{
    if (iree_hal_debug_ExportDef_start(B)
        || iree_hal_debug_ExportDef_name_add(B, v0)
        || iree_hal_debug_ExportDef_location_add(B, v1)
        || iree_hal_debug_ExportDef_stage_locations_add(B, v2)) {
        return 0;
    }
    return iree_hal_debug_ExportDef_end(B);
}

static iree_hal_debug_ExportDef_ref_t iree_hal_debug_ExportDef_clone(flatbuffers_builder_t *B, iree_hal_debug_ExportDef_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (iree_hal_debug_ExportDef_start(B)
        || iree_hal_debug_ExportDef_name_pick(B, t)
        || iree_hal_debug_ExportDef_location_pick(B, t)
        || iree_hal_debug_ExportDef_stage_locations_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, iree_hal_debug_ExportDef_end(B));
}

__flatbuffers_build_string_field(0, flatbuffers_, iree_hal_debug_SourceFileDef_path, iree_hal_debug_SourceFileDef)
__flatbuffers_build_vector_field(1, flatbuffers_, iree_hal_debug_SourceFileDef_content, flatbuffers_uint8, uint8_t, iree_hal_debug_SourceFileDef)

static inline iree_hal_debug_SourceFileDef_ref_t iree_hal_debug_SourceFileDef_create(flatbuffers_builder_t *B __iree_hal_debug_SourceFileDef_formal_args)
{
    if (iree_hal_debug_SourceFileDef_start(B)
        || iree_hal_debug_SourceFileDef_path_add(B, v0)
        || iree_hal_debug_SourceFileDef_content_add(B, v1)) {
        return 0;
    }
    return iree_hal_debug_SourceFileDef_end(B);
}

static iree_hal_debug_SourceFileDef_ref_t iree_hal_debug_SourceFileDef_clone(flatbuffers_builder_t *B, iree_hal_debug_SourceFileDef_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (iree_hal_debug_SourceFileDef_start(B)
        || iree_hal_debug_SourceFileDef_path_pick(B, t)
        || iree_hal_debug_SourceFileDef_content_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, iree_hal_debug_SourceFileDef_end(B));
}

#include "flatcc/flatcc_epilogue.h"
#endif /* EXECUTABLE_DEBUG_INFO_BUILDER_H */
