#ifndef EXECUTABLE_DEBUG_INFO_JSON_PRINTER_H
#define EXECUTABLE_DEBUG_INFO_JSON_PRINTER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#include "flatcc/flatcc_json_printer.h"
#include "flatcc/flatcc_prologue.h"

static void iree_hal_debug_FileLineLocDef_print_json_table(flatcc_json_printer_t *ctx, flatcc_json_printer_table_descriptor_t *td);
static void iree_hal_debug_StageLocationDef_print_json_table(flatcc_json_printer_t *ctx, flatcc_json_printer_table_descriptor_t *td);
static void iree_hal_debug_ExportDef_print_json_table(flatcc_json_printer_t *ctx, flatcc_json_printer_table_descriptor_t *td);
static void iree_hal_debug_SourceFileDef_print_json_table(flatcc_json_printer_t *ctx, flatcc_json_printer_table_descriptor_t *td);

static void iree_hal_debug_FileLineLocDef_print_json_table(flatcc_json_printer_t *ctx, flatcc_json_printer_table_descriptor_t *td)
{
    flatcc_json_printer_string_field(ctx, td, 0, "filename", 8);
    flatcc_json_printer_int32_field(ctx, td, 1, "line", 4, INT32_C(0));
}

static inline int iree_hal_debug_FileLineLocDef_print_json_as_root(flatcc_json_printer_t *ctx, const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_json_printer_table_as_root(ctx, buf, bufsiz, fid, iree_hal_debug_FileLineLocDef_print_json_table);
}

static void iree_hal_debug_StageLocationDef_print_json_table(flatcc_json_printer_t *ctx, flatcc_json_printer_table_descriptor_t *td)
{
    flatcc_json_printer_string_field(ctx, td, 0, "stage", 5);
    flatcc_json_printer_table_field(ctx, td, 1, "location", 8, iree_hal_debug_FileLineLocDef_print_json_table);
}

static inline int iree_hal_debug_StageLocationDef_print_json_as_root(flatcc_json_printer_t *ctx, const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_json_printer_table_as_root(ctx, buf, bufsiz, fid, iree_hal_debug_StageLocationDef_print_json_table);
}

static void iree_hal_debug_ExportDef_print_json_table(flatcc_json_printer_t *ctx, flatcc_json_printer_table_descriptor_t *td)
{
    flatcc_json_printer_string_field(ctx, td, 0, "name", 4);
    flatcc_json_printer_table_field(ctx, td, 1, "location", 8, iree_hal_debug_FileLineLocDef_print_json_table);
    flatcc_json_printer_table_vector_field(ctx, td, 2, "stage_locations", 15, iree_hal_debug_StageLocationDef_print_json_table);
}

static inline int iree_hal_debug_ExportDef_print_json_as_root(flatcc_json_printer_t *ctx, const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_json_printer_table_as_root(ctx, buf, bufsiz, fid, iree_hal_debug_ExportDef_print_json_table);
}

static void iree_hal_debug_SourceFileDef_print_json_table(flatcc_json_printer_t *ctx, flatcc_json_printer_table_descriptor_t *td)
{
    flatcc_json_printer_string_field(ctx, td, 0, "path", 4);
    flatcc_json_printer_uint8_vector_field(ctx, td, 1, "content", 7);
}

static inline int iree_hal_debug_SourceFileDef_print_json_as_root(flatcc_json_printer_t *ctx, const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_json_printer_table_as_root(ctx, buf, bufsiz, fid, iree_hal_debug_SourceFileDef_print_json_table);
}

#include "flatcc/flatcc_epilogue.h"
#endif /* EXECUTABLE_DEBUG_INFO_JSON_PRINTER_H */
