#ifndef VULKAN_EXECUTABLE_DEF_JSON_PRINTER_H
#define VULKAN_EXECUTABLE_DEF_JSON_PRINTER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#include "flatcc/flatcc_json_printer.h"
#ifndef EXECUTABLE_DEBUG_INFO_JSON_PRINTER_H
#include "executable_debug_info_json_printer.h"
#endif
#include "flatcc/flatcc_prologue.h"

/*
 * Prints the default root table or struct from a buffer which must have
 * the schema declared file identifier, if any. It is also possible to
 * call the type specific `print_json_as_root` function wich accepts an
 * optional identifier (or 0) as argument. The printer `ctx` object must
 * be initialized with the appropriate output type, or it can be 0 which
 * defaults to stdout. NOTE: `ctx` is not generally allowed to be null, only
 * here for a simplified interface.
 */
static int vulkan_executable_def_print_json(flatcc_json_printer_t *ctx, const char *buf, size_t bufsiz);

static void iree_hal_vulkan_PushConstantRange_print_json_struct(flatcc_json_printer_t *ctx, const void *p);
static void iree_hal_vulkan_DescriptorSetLayoutBindingDef_print_json_table(flatcc_json_printer_t *ctx, flatcc_json_printer_table_descriptor_t *td);
static void iree_hal_vulkan_DescriptorSetLayoutDef_print_json_table(flatcc_json_printer_t *ctx, flatcc_json_printer_table_descriptor_t *td);
static void iree_hal_vulkan_PipelineLayoutDef_print_json_table(flatcc_json_printer_t *ctx, flatcc_json_printer_table_descriptor_t *td);
static void iree_hal_vulkan_ShaderModuleDef_print_json_table(flatcc_json_printer_t *ctx, flatcc_json_printer_table_descriptor_t *td);
static void iree_hal_vulkan_PipelineDef_print_json_table(flatcc_json_printer_t *ctx, flatcc_json_printer_table_descriptor_t *td);
static void iree_hal_vulkan_ExecutableDef_print_json_table(flatcc_json_printer_t *ctx, flatcc_json_printer_table_descriptor_t *td);

static void iree_hal_vulkan_VkDescriptorType_print_json_enum(flatcc_json_printer_t *ctx, uint32_t v)
{

    switch (v) {
    case (0): flatcc_json_printer_enum(ctx, "SAMPLER", 7); break;
    case (6): flatcc_json_printer_enum(ctx, "UNIFORM_BUFFER", 14); break;
    case (7): flatcc_json_printer_enum(ctx, "STORAGE_BUFFER", 14); break;
    default: flatcc_json_printer_uint32(ctx, v); break;
    }
}

static void iree_hal_vulkan_PushConstantRange_print_json_struct(flatcc_json_printer_t *ctx, const void *p)
{
    flatcc_json_printer_uint32_struct_field(ctx, 0, p, 0, "stage_flags", 11);
    flatcc_json_printer_uint32_struct_field(ctx, 1, p, 4, "offset", 6);
    flatcc_json_printer_uint32_struct_field(ctx, 2, p, 8, "size", 4);
}

static inline int iree_hal_vulkan_PushConstantRange_print_json_as_root(flatcc_json_printer_t *ctx, const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_json_printer_struct_as_root(ctx, buf, bufsiz, fid, iree_hal_vulkan_PushConstantRange_print_json_struct);
}

static void iree_hal_vulkan_DescriptorSetLayoutBindingDef_print_json_table(flatcc_json_printer_t *ctx, flatcc_json_printer_table_descriptor_t *td)
{
    flatcc_json_printer_uint32_field(ctx, td, 0, "binding", 7, UINT32_C(0));
    flatcc_json_printer_uint32_enum_field(ctx, td, 1, "descriptor_type", 15, UINT32_C(0), iree_hal_vulkan_VkDescriptorType_print_json_enum);
    flatcc_json_printer_uint32_field(ctx, td, 2, "descriptor_count", 16, UINT32_C(0));
    flatcc_json_printer_uint32_field(ctx, td, 3, "stage_flags", 11, UINT32_C(0));
}

static inline int iree_hal_vulkan_DescriptorSetLayoutBindingDef_print_json_as_root(flatcc_json_printer_t *ctx, const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_json_printer_table_as_root(ctx, buf, bufsiz, fid, iree_hal_vulkan_DescriptorSetLayoutBindingDef_print_json_table);
}

static void iree_hal_vulkan_DescriptorSetLayoutDef_print_json_table(flatcc_json_printer_t *ctx, flatcc_json_printer_table_descriptor_t *td)
{
    flatcc_json_printer_table_vector_field(ctx, td, 0, "bindings", 8, iree_hal_vulkan_DescriptorSetLayoutBindingDef_print_json_table);
}

static inline int iree_hal_vulkan_DescriptorSetLayoutDef_print_json_as_root(flatcc_json_printer_t *ctx, const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_json_printer_table_as_root(ctx, buf, bufsiz, fid, iree_hal_vulkan_DescriptorSetLayoutDef_print_json_table);
}

static void iree_hal_vulkan_PipelineLayoutDef_print_json_table(flatcc_json_printer_t *ctx, flatcc_json_printer_table_descriptor_t *td)
{
    flatcc_json_printer_uint32_vector_field(ctx, td, 0, "descriptor_set_layout_ordinals", 30);
    flatcc_json_printer_struct_vector_field(ctx, td, 1, "push_constant_ranges", 20, 12, iree_hal_vulkan_PushConstantRange_print_json_struct);
}

static inline int iree_hal_vulkan_PipelineLayoutDef_print_json_as_root(flatcc_json_printer_t *ctx, const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_json_printer_table_as_root(ctx, buf, bufsiz, fid, iree_hal_vulkan_PipelineLayoutDef_print_json_table);
}

static void iree_hal_vulkan_ShaderModuleDef_print_json_table(flatcc_json_printer_t *ctx, flatcc_json_printer_table_descriptor_t *td)
{
    flatcc_json_printer_uint32_vector_field(ctx, td, 0, "spirv_code", 10);
}

static inline int iree_hal_vulkan_ShaderModuleDef_print_json_as_root(flatcc_json_printer_t *ctx, const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_json_printer_table_as_root(ctx, buf, bufsiz, fid, iree_hal_vulkan_ShaderModuleDef_print_json_table);
}

static void iree_hal_vulkan_PipelineDef_print_json_table(flatcc_json_printer_t *ctx, flatcc_json_printer_table_descriptor_t *td)
{
    flatcc_json_printer_uint32_field(ctx, td, 0, "shader_module_ordinal", 21, UINT32_C(0));
    flatcc_json_printer_string_field(ctx, td, 1, "entry_point", 11);
    flatcc_json_printer_uint32_field(ctx, td, 2, "pipeline_layout_ordinal", 23, UINT32_C(0));
    flatcc_json_printer_uint32_field(ctx, td, 3, "subgroup_size", 13, UINT32_C(0));
    flatcc_json_printer_table_field(ctx, td, 4, "debug_info", 10, iree_hal_debug_ExportDef_print_json_table);
}

static inline int iree_hal_vulkan_PipelineDef_print_json_as_root(flatcc_json_printer_t *ctx, const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_json_printer_table_as_root(ctx, buf, bufsiz, fid, iree_hal_vulkan_PipelineDef_print_json_table);
}

static void iree_hal_vulkan_ExecutableDef_print_json_table(flatcc_json_printer_t *ctx, flatcc_json_printer_table_descriptor_t *td)
{
    flatcc_json_printer_table_vector_field(ctx, td, 0, "pipelines", 9, iree_hal_vulkan_PipelineDef_print_json_table);
    flatcc_json_printer_table_vector_field(ctx, td, 1, "descriptor_set_layouts", 22, iree_hal_vulkan_DescriptorSetLayoutDef_print_json_table);
    flatcc_json_printer_table_vector_field(ctx, td, 2, "pipeline_layouts", 16, iree_hal_vulkan_PipelineLayoutDef_print_json_table);
    flatcc_json_printer_table_vector_field(ctx, td, 3, "shader_modules", 14, iree_hal_vulkan_ShaderModuleDef_print_json_table);
    flatcc_json_printer_table_vector_field(ctx, td, 4, "source_files", 12, iree_hal_debug_SourceFileDef_print_json_table);
}

static inline int iree_hal_vulkan_ExecutableDef_print_json_as_root(flatcc_json_printer_t *ctx, const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_json_printer_table_as_root(ctx, buf, bufsiz, fid, iree_hal_vulkan_ExecutableDef_print_json_table);
}

static int vulkan_executable_def_print_json(flatcc_json_printer_t *ctx, const char *buf, size_t bufsiz)
{
    flatcc_json_printer_t printer;

    if (ctx == 0) {
        ctx = &printer;
        flatcc_json_printer_init(ctx, 0);
    }
    return iree_hal_vulkan_ExecutableDef_print_json_as_root(ctx, buf, bufsiz, "VKE1");
}

#include "flatcc/flatcc_epilogue.h"
#endif /* VULKAN_EXECUTABLE_DEF_JSON_PRINTER_H */
