#ifndef VULKAN_EXECUTABLE_DEF_BUILDER_H
#define VULKAN_EXECUTABLE_DEF_BUILDER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef VULKAN_EXECUTABLE_DEF_READER_H
#include "vulkan_executable_def_reader.h"
#endif
#ifndef FLATBUFFERS_COMMON_BUILDER_H
#include "flatbuffers_common_builder.h"
#endif
#ifndef EXECUTABLE_DEBUG_INFO_BUILDER_H
#include "executable_debug_info_builder.h"
#endif
#include "flatcc/flatcc_prologue.h"
#undef flatbuffers_identifier
#define flatbuffers_identifier "VKE1"
#undef flatbuffers_extension
#define flatbuffers_extension "vk1"

#define __iree_hal_vulkan_VkDescriptorType_formal_args , iree_hal_vulkan_VkDescriptorType_enum_t v0
#define __iree_hal_vulkan_VkDescriptorType_call_args , v0
__flatbuffers_build_scalar(flatbuffers_, iree_hal_vulkan_VkDescriptorType, iree_hal_vulkan_VkDescriptorType_enum_t)

#define __iree_hal_vulkan_PushConstantRange_formal_args , uint32_t v0, uint32_t v1, uint32_t v2
#define __iree_hal_vulkan_PushConstantRange_call_args , v0, v1, v2
static inline iree_hal_vulkan_PushConstantRange_t *iree_hal_vulkan_PushConstantRange_assign(iree_hal_vulkan_PushConstantRange_t *p, uint32_t v0, uint32_t v1, uint32_t v2)
{ p->stage_flags = v0; p->offset = v1; p->size = v2;
  return p; }
static inline iree_hal_vulkan_PushConstantRange_t *iree_hal_vulkan_PushConstantRange_copy(iree_hal_vulkan_PushConstantRange_t *p, const iree_hal_vulkan_PushConstantRange_t *p2)
{ p->stage_flags = p2->stage_flags; p->offset = p2->offset; p->size = p2->size;
  return p; }
static inline iree_hal_vulkan_PushConstantRange_t *iree_hal_vulkan_PushConstantRange_assign_to_pe(iree_hal_vulkan_PushConstantRange_t *p, uint32_t v0, uint32_t v1, uint32_t v2)
{ flatbuffers_uint32_assign_to_pe(&p->stage_flags, v0); flatbuffers_uint32_assign_to_pe(&p->offset, v1); flatbuffers_uint32_assign_to_pe(&p->size, v2);
  return p; }
static inline iree_hal_vulkan_PushConstantRange_t *iree_hal_vulkan_PushConstantRange_copy_to_pe(iree_hal_vulkan_PushConstantRange_t *p, const iree_hal_vulkan_PushConstantRange_t *p2)
{ flatbuffers_uint32_copy_to_pe(&p->stage_flags, &p2->stage_flags); flatbuffers_uint32_copy_to_pe(&p->offset, &p2->offset); flatbuffers_uint32_copy_to_pe(&p->size, &p2->size);
  return p; }
static inline iree_hal_vulkan_PushConstantRange_t *iree_hal_vulkan_PushConstantRange_assign_from_pe(iree_hal_vulkan_PushConstantRange_t *p, uint32_t v0, uint32_t v1, uint32_t v2)
{ flatbuffers_uint32_assign_from_pe(&p->stage_flags, v0); flatbuffers_uint32_assign_from_pe(&p->offset, v1); flatbuffers_uint32_assign_from_pe(&p->size, v2);
  return p; }
static inline iree_hal_vulkan_PushConstantRange_t *iree_hal_vulkan_PushConstantRange_copy_from_pe(iree_hal_vulkan_PushConstantRange_t *p, const iree_hal_vulkan_PushConstantRange_t *p2)
{ flatbuffers_uint32_copy_from_pe(&p->stage_flags, &p2->stage_flags); flatbuffers_uint32_copy_from_pe(&p->offset, &p2->offset); flatbuffers_uint32_copy_from_pe(&p->size, &p2->size);
  return p; }
__flatbuffers_build_struct(flatbuffers_, iree_hal_vulkan_PushConstantRange, 12, 4, iree_hal_vulkan_PushConstantRange_file_identifier, iree_hal_vulkan_PushConstantRange_type_identifier)
__flatbuffers_define_fixed_array_primitives(flatbuffers_, iree_hal_vulkan_PushConstantRange, iree_hal_vulkan_PushConstantRange_t)

static const flatbuffers_voffset_t __iree_hal_vulkan_DescriptorSetLayoutBindingDef_required[] = { 0 };
typedef flatbuffers_ref_t iree_hal_vulkan_DescriptorSetLayoutBindingDef_ref_t;
static iree_hal_vulkan_DescriptorSetLayoutBindingDef_ref_t iree_hal_vulkan_DescriptorSetLayoutBindingDef_clone(flatbuffers_builder_t *B, iree_hal_vulkan_DescriptorSetLayoutBindingDef_table_t t);
__flatbuffers_build_table(flatbuffers_, iree_hal_vulkan_DescriptorSetLayoutBindingDef, 4)

static const flatbuffers_voffset_t __iree_hal_vulkan_DescriptorSetLayoutDef_required[] = { 0 };
typedef flatbuffers_ref_t iree_hal_vulkan_DescriptorSetLayoutDef_ref_t;
static iree_hal_vulkan_DescriptorSetLayoutDef_ref_t iree_hal_vulkan_DescriptorSetLayoutDef_clone(flatbuffers_builder_t *B, iree_hal_vulkan_DescriptorSetLayoutDef_table_t t);
__flatbuffers_build_table(flatbuffers_, iree_hal_vulkan_DescriptorSetLayoutDef, 1)

static const flatbuffers_voffset_t __iree_hal_vulkan_PipelineLayoutDef_required[] = { 0 };
typedef flatbuffers_ref_t iree_hal_vulkan_PipelineLayoutDef_ref_t;
static iree_hal_vulkan_PipelineLayoutDef_ref_t iree_hal_vulkan_PipelineLayoutDef_clone(flatbuffers_builder_t *B, iree_hal_vulkan_PipelineLayoutDef_table_t t);
__flatbuffers_build_table(flatbuffers_, iree_hal_vulkan_PipelineLayoutDef, 2)

static const flatbuffers_voffset_t __iree_hal_vulkan_ShaderModuleDef_required[] = { 0 };
typedef flatbuffers_ref_t iree_hal_vulkan_ShaderModuleDef_ref_t;
static iree_hal_vulkan_ShaderModuleDef_ref_t iree_hal_vulkan_ShaderModuleDef_clone(flatbuffers_builder_t *B, iree_hal_vulkan_ShaderModuleDef_table_t t);
__flatbuffers_build_table(flatbuffers_, iree_hal_vulkan_ShaderModuleDef, 1)

static const flatbuffers_voffset_t __iree_hal_vulkan_PipelineDef_required[] = { 0 };
typedef flatbuffers_ref_t iree_hal_vulkan_PipelineDef_ref_t;
static iree_hal_vulkan_PipelineDef_ref_t iree_hal_vulkan_PipelineDef_clone(flatbuffers_builder_t *B, iree_hal_vulkan_PipelineDef_table_t t);
__flatbuffers_build_table(flatbuffers_, iree_hal_vulkan_PipelineDef, 5)

static const flatbuffers_voffset_t __iree_hal_vulkan_ExecutableDef_required[] = { 0 };
typedef flatbuffers_ref_t iree_hal_vulkan_ExecutableDef_ref_t;
static iree_hal_vulkan_ExecutableDef_ref_t iree_hal_vulkan_ExecutableDef_clone(flatbuffers_builder_t *B, iree_hal_vulkan_ExecutableDef_table_t t);
__flatbuffers_build_table(flatbuffers_, iree_hal_vulkan_ExecutableDef, 5)

#define __iree_hal_vulkan_DescriptorSetLayoutBindingDef_formal_args , uint32_t v0, iree_hal_vulkan_VkDescriptorType_enum_t v1, uint32_t v2, uint32_t v3
#define __iree_hal_vulkan_DescriptorSetLayoutBindingDef_call_args , v0, v1, v2, v3
static inline iree_hal_vulkan_DescriptorSetLayoutBindingDef_ref_t iree_hal_vulkan_DescriptorSetLayoutBindingDef_create(flatbuffers_builder_t *B __iree_hal_vulkan_DescriptorSetLayoutBindingDef_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, iree_hal_vulkan_DescriptorSetLayoutBindingDef, iree_hal_vulkan_DescriptorSetLayoutBindingDef_file_identifier, iree_hal_vulkan_DescriptorSetLayoutBindingDef_type_identifier)

#define __iree_hal_vulkan_DescriptorSetLayoutDef_formal_args , iree_hal_vulkan_DescriptorSetLayoutBindingDef_vec_ref_t v0
#define __iree_hal_vulkan_DescriptorSetLayoutDef_call_args , v0
static inline iree_hal_vulkan_DescriptorSetLayoutDef_ref_t iree_hal_vulkan_DescriptorSetLayoutDef_create(flatbuffers_builder_t *B __iree_hal_vulkan_DescriptorSetLayoutDef_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, iree_hal_vulkan_DescriptorSetLayoutDef, iree_hal_vulkan_DescriptorSetLayoutDef_file_identifier, iree_hal_vulkan_DescriptorSetLayoutDef_type_identifier)

#define __iree_hal_vulkan_PipelineLayoutDef_formal_args , flatbuffers_uint32_vec_ref_t v0, iree_hal_vulkan_PushConstantRange_vec_ref_t v1
#define __iree_hal_vulkan_PipelineLayoutDef_call_args , v0, v1
static inline iree_hal_vulkan_PipelineLayoutDef_ref_t iree_hal_vulkan_PipelineLayoutDef_create(flatbuffers_builder_t *B __iree_hal_vulkan_PipelineLayoutDef_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, iree_hal_vulkan_PipelineLayoutDef, iree_hal_vulkan_PipelineLayoutDef_file_identifier, iree_hal_vulkan_PipelineLayoutDef_type_identifier)

#define __iree_hal_vulkan_ShaderModuleDef_formal_args , flatbuffers_uint32_vec_ref_t v0
#define __iree_hal_vulkan_ShaderModuleDef_call_args , v0
static inline iree_hal_vulkan_ShaderModuleDef_ref_t iree_hal_vulkan_ShaderModuleDef_create(flatbuffers_builder_t *B __iree_hal_vulkan_ShaderModuleDef_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, iree_hal_vulkan_ShaderModuleDef, iree_hal_vulkan_ShaderModuleDef_file_identifier, iree_hal_vulkan_ShaderModuleDef_type_identifier)

#define __iree_hal_vulkan_PipelineDef_formal_args ,\
  uint32_t v0, flatbuffers_string_ref_t v1, uint32_t v2, uint32_t v3, iree_hal_debug_ExportDef_ref_t v4
#define __iree_hal_vulkan_PipelineDef_call_args ,\
  v0, v1, v2, v3, v4
static inline iree_hal_vulkan_PipelineDef_ref_t iree_hal_vulkan_PipelineDef_create(flatbuffers_builder_t *B __iree_hal_vulkan_PipelineDef_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, iree_hal_vulkan_PipelineDef, iree_hal_vulkan_PipelineDef_file_identifier, iree_hal_vulkan_PipelineDef_type_identifier)

#define __iree_hal_vulkan_ExecutableDef_formal_args ,\
  iree_hal_vulkan_PipelineDef_vec_ref_t v0, iree_hal_vulkan_DescriptorSetLayoutDef_vec_ref_t v1, iree_hal_vulkan_PipelineLayoutDef_vec_ref_t v2, iree_hal_vulkan_ShaderModuleDef_vec_ref_t v3, iree_hal_debug_SourceFileDef_vec_ref_t v4
#define __iree_hal_vulkan_ExecutableDef_call_args ,\
  v0, v1, v2, v3, v4
static inline iree_hal_vulkan_ExecutableDef_ref_t iree_hal_vulkan_ExecutableDef_create(flatbuffers_builder_t *B __iree_hal_vulkan_ExecutableDef_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, iree_hal_vulkan_ExecutableDef, iree_hal_vulkan_ExecutableDef_file_identifier, iree_hal_vulkan_ExecutableDef_type_identifier)

__flatbuffers_build_scalar_field(0, flatbuffers_, iree_hal_vulkan_DescriptorSetLayoutBindingDef_binding, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), iree_hal_vulkan_DescriptorSetLayoutBindingDef)
__flatbuffers_build_scalar_field(1, flatbuffers_, iree_hal_vulkan_DescriptorSetLayoutBindingDef_descriptor_type, iree_hal_vulkan_VkDescriptorType, iree_hal_vulkan_VkDescriptorType_enum_t, 4, 4, UINT32_C(0), iree_hal_vulkan_DescriptorSetLayoutBindingDef)
__flatbuffers_build_scalar_field(2, flatbuffers_, iree_hal_vulkan_DescriptorSetLayoutBindingDef_descriptor_count, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), iree_hal_vulkan_DescriptorSetLayoutBindingDef)
__flatbuffers_build_scalar_field(3, flatbuffers_, iree_hal_vulkan_DescriptorSetLayoutBindingDef_stage_flags, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), iree_hal_vulkan_DescriptorSetLayoutBindingDef)

static inline iree_hal_vulkan_DescriptorSetLayoutBindingDef_ref_t iree_hal_vulkan_DescriptorSetLayoutBindingDef_create(flatbuffers_builder_t *B __iree_hal_vulkan_DescriptorSetLayoutBindingDef_formal_args)
{
    if (iree_hal_vulkan_DescriptorSetLayoutBindingDef_start(B)
        || iree_hal_vulkan_DescriptorSetLayoutBindingDef_binding_add(B, v0)
        || iree_hal_vulkan_DescriptorSetLayoutBindingDef_descriptor_type_add(B, v1)
        || iree_hal_vulkan_DescriptorSetLayoutBindingDef_descriptor_count_add(B, v2)
        || iree_hal_vulkan_DescriptorSetLayoutBindingDef_stage_flags_add(B, v3)) {
        return 0;
    }
    return iree_hal_vulkan_DescriptorSetLayoutBindingDef_end(B);
}

static iree_hal_vulkan_DescriptorSetLayoutBindingDef_ref_t iree_hal_vulkan_DescriptorSetLayoutBindingDef_clone(flatbuffers_builder_t *B, iree_hal_vulkan_DescriptorSetLayoutBindingDef_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (iree_hal_vulkan_DescriptorSetLayoutBindingDef_start(B)
        || iree_hal_vulkan_DescriptorSetLayoutBindingDef_binding_pick(B, t)
        || iree_hal_vulkan_DescriptorSetLayoutBindingDef_descriptor_type_pick(B, t)
        || iree_hal_vulkan_DescriptorSetLayoutBindingDef_descriptor_count_pick(B, t)
        || iree_hal_vulkan_DescriptorSetLayoutBindingDef_stage_flags_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, iree_hal_vulkan_DescriptorSetLayoutBindingDef_end(B));
}

__flatbuffers_build_table_vector_field(0, flatbuffers_, iree_hal_vulkan_DescriptorSetLayoutDef_bindings, iree_hal_vulkan_DescriptorSetLayoutBindingDef, iree_hal_vulkan_DescriptorSetLayoutDef)

static inline iree_hal_vulkan_DescriptorSetLayoutDef_ref_t iree_hal_vulkan_DescriptorSetLayoutDef_create(flatbuffers_builder_t *B __iree_hal_vulkan_DescriptorSetLayoutDef_formal_args)
{
    if (iree_hal_vulkan_DescriptorSetLayoutDef_start(B)
        || iree_hal_vulkan_DescriptorSetLayoutDef_bindings_add(B, v0)) {
        return 0;
    }
    return iree_hal_vulkan_DescriptorSetLayoutDef_end(B);
}

static iree_hal_vulkan_DescriptorSetLayoutDef_ref_t iree_hal_vulkan_DescriptorSetLayoutDef_clone(flatbuffers_builder_t *B, iree_hal_vulkan_DescriptorSetLayoutDef_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (iree_hal_vulkan_DescriptorSetLayoutDef_start(B)
        || iree_hal_vulkan_DescriptorSetLayoutDef_bindings_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, iree_hal_vulkan_DescriptorSetLayoutDef_end(B));
}

__flatbuffers_build_vector_field(0, flatbuffers_, iree_hal_vulkan_PipelineLayoutDef_descriptor_set_layout_ordinals, flatbuffers_uint32, uint32_t, iree_hal_vulkan_PipelineLayoutDef)
__flatbuffers_build_vector_field(1, flatbuffers_, iree_hal_vulkan_PipelineLayoutDef_push_constant_ranges, iree_hal_vulkan_PushConstantRange, iree_hal_vulkan_PushConstantRange_t, iree_hal_vulkan_PipelineLayoutDef)

static inline iree_hal_vulkan_PipelineLayoutDef_ref_t iree_hal_vulkan_PipelineLayoutDef_create(flatbuffers_builder_t *B __iree_hal_vulkan_PipelineLayoutDef_formal_args)
{
    if (iree_hal_vulkan_PipelineLayoutDef_start(B)
        || iree_hal_vulkan_PipelineLayoutDef_descriptor_set_layout_ordinals_add(B, v0)
        || iree_hal_vulkan_PipelineLayoutDef_push_constant_ranges_add(B, v1)) {
        return 0;
    }
    return iree_hal_vulkan_PipelineLayoutDef_end(B);
}

static iree_hal_vulkan_PipelineLayoutDef_ref_t iree_hal_vulkan_PipelineLayoutDef_clone(flatbuffers_builder_t *B, iree_hal_vulkan_PipelineLayoutDef_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (iree_hal_vulkan_PipelineLayoutDef_start(B)
        || iree_hal_vulkan_PipelineLayoutDef_descriptor_set_layout_ordinals_pick(B, t)
        || iree_hal_vulkan_PipelineLayoutDef_push_constant_ranges_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, iree_hal_vulkan_PipelineLayoutDef_end(B));
}

__flatbuffers_build_vector_field(0, flatbuffers_, iree_hal_vulkan_ShaderModuleDef_spirv_code, flatbuffers_uint32, uint32_t, iree_hal_vulkan_ShaderModuleDef)

static inline iree_hal_vulkan_ShaderModuleDef_ref_t iree_hal_vulkan_ShaderModuleDef_create(flatbuffers_builder_t *B __iree_hal_vulkan_ShaderModuleDef_formal_args)
{
    if (iree_hal_vulkan_ShaderModuleDef_start(B)
        || iree_hal_vulkan_ShaderModuleDef_spirv_code_add(B, v0)) {
        return 0;
    }
    return iree_hal_vulkan_ShaderModuleDef_end(B);
}

static iree_hal_vulkan_ShaderModuleDef_ref_t iree_hal_vulkan_ShaderModuleDef_clone(flatbuffers_builder_t *B, iree_hal_vulkan_ShaderModuleDef_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (iree_hal_vulkan_ShaderModuleDef_start(B)
        || iree_hal_vulkan_ShaderModuleDef_spirv_code_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, iree_hal_vulkan_ShaderModuleDef_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, iree_hal_vulkan_PipelineDef_shader_module_ordinal, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), iree_hal_vulkan_PipelineDef)
__flatbuffers_build_string_field(1, flatbuffers_, iree_hal_vulkan_PipelineDef_entry_point, iree_hal_vulkan_PipelineDef)
__flatbuffers_build_scalar_field(2, flatbuffers_, iree_hal_vulkan_PipelineDef_pipeline_layout_ordinal, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), iree_hal_vulkan_PipelineDef)
__flatbuffers_build_scalar_field(3, flatbuffers_, iree_hal_vulkan_PipelineDef_subgroup_size, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), iree_hal_vulkan_PipelineDef)
__flatbuffers_build_table_field(4, flatbuffers_, iree_hal_vulkan_PipelineDef_debug_info, iree_hal_debug_ExportDef, iree_hal_vulkan_PipelineDef)

static inline iree_hal_vulkan_PipelineDef_ref_t iree_hal_vulkan_PipelineDef_create(flatbuffers_builder_t *B __iree_hal_vulkan_PipelineDef_formal_args)
{
    if (iree_hal_vulkan_PipelineDef_start(B)
        || iree_hal_vulkan_PipelineDef_shader_module_ordinal_add(B, v0)
        || iree_hal_vulkan_PipelineDef_entry_point_add(B, v1)
        || iree_hal_vulkan_PipelineDef_pipeline_layout_ordinal_add(B, v2)
        || iree_hal_vulkan_PipelineDef_subgroup_size_add(B, v3)
        || iree_hal_vulkan_PipelineDef_debug_info_add(B, v4)) {
        return 0;
    }
    return iree_hal_vulkan_PipelineDef_end(B);
}

static iree_hal_vulkan_PipelineDef_ref_t iree_hal_vulkan_PipelineDef_clone(flatbuffers_builder_t *B, iree_hal_vulkan_PipelineDef_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (iree_hal_vulkan_PipelineDef_start(B)
        || iree_hal_vulkan_PipelineDef_shader_module_ordinal_pick(B, t)
        || iree_hal_vulkan_PipelineDef_entry_point_pick(B, t)
        || iree_hal_vulkan_PipelineDef_pipeline_layout_ordinal_pick(B, t)
        || iree_hal_vulkan_PipelineDef_subgroup_size_pick(B, t)
        || iree_hal_vulkan_PipelineDef_debug_info_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, iree_hal_vulkan_PipelineDef_end(B));
}

__flatbuffers_build_table_vector_field(0, flatbuffers_, iree_hal_vulkan_ExecutableDef_pipelines, iree_hal_vulkan_PipelineDef, iree_hal_vulkan_ExecutableDef)
__flatbuffers_build_table_vector_field(1, flatbuffers_, iree_hal_vulkan_ExecutableDef_descriptor_set_layouts, iree_hal_vulkan_DescriptorSetLayoutDef, iree_hal_vulkan_ExecutableDef)
__flatbuffers_build_table_vector_field(2, flatbuffers_, iree_hal_vulkan_ExecutableDef_pipeline_layouts, iree_hal_vulkan_PipelineLayoutDef, iree_hal_vulkan_ExecutableDef)
__flatbuffers_build_table_vector_field(3, flatbuffers_, iree_hal_vulkan_ExecutableDef_shader_modules, iree_hal_vulkan_ShaderModuleDef, iree_hal_vulkan_ExecutableDef)
__flatbuffers_build_table_vector_field(4, flatbuffers_, iree_hal_vulkan_ExecutableDef_source_files, iree_hal_debug_SourceFileDef, iree_hal_vulkan_ExecutableDef)

static inline iree_hal_vulkan_ExecutableDef_ref_t iree_hal_vulkan_ExecutableDef_create(flatbuffers_builder_t *B __iree_hal_vulkan_ExecutableDef_formal_args)
{
    if (iree_hal_vulkan_ExecutableDef_start(B)
        || iree_hal_vulkan_ExecutableDef_pipelines_add(B, v0)
        || iree_hal_vulkan_ExecutableDef_descriptor_set_layouts_add(B, v1)
        || iree_hal_vulkan_ExecutableDef_pipeline_layouts_add(B, v2)
        || iree_hal_vulkan_ExecutableDef_shader_modules_add(B, v3)
        || iree_hal_vulkan_ExecutableDef_source_files_add(B, v4)) {
        return 0;
    }
    return iree_hal_vulkan_ExecutableDef_end(B);
}

static iree_hal_vulkan_ExecutableDef_ref_t iree_hal_vulkan_ExecutableDef_clone(flatbuffers_builder_t *B, iree_hal_vulkan_ExecutableDef_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (iree_hal_vulkan_ExecutableDef_start(B)
        || iree_hal_vulkan_ExecutableDef_pipelines_pick(B, t)
        || iree_hal_vulkan_ExecutableDef_descriptor_set_layouts_pick(B, t)
        || iree_hal_vulkan_ExecutableDef_pipeline_layouts_pick(B, t)
        || iree_hal_vulkan_ExecutableDef_shader_modules_pick(B, t)
        || iree_hal_vulkan_ExecutableDef_source_files_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, iree_hal_vulkan_ExecutableDef_end(B));
}

#include "flatcc/flatcc_epilogue.h"
#endif /* VULKAN_EXECUTABLE_DEF_BUILDER_H */
