#ifndef VULKAN_EXECUTABLE_DEF_VERIFIER_H
#define VULKAN_EXECUTABLE_DEF_VERIFIER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef VULKAN_EXECUTABLE_DEF_READER_H
#include "vulkan_executable_def_reader.h"
#endif
#include "flatcc/flatcc_verifier.h"
#ifndef EXECUTABLE_DEBUG_INFO_VERIFIER_H
#include "executable_debug_info_verifier.h"
#endif
#include "flatcc/flatcc_prologue.h"

static int iree_hal_vulkan_DescriptorSetLayoutBindingDef_verify_table(flatcc_table_verifier_descriptor_t *td);
static int iree_hal_vulkan_DescriptorSetLayoutDef_verify_table(flatcc_table_verifier_descriptor_t *td);
static int iree_hal_vulkan_PipelineLayoutDef_verify_table(flatcc_table_verifier_descriptor_t *td);
static int iree_hal_vulkan_ShaderModuleDef_verify_table(flatcc_table_verifier_descriptor_t *td);
static int iree_hal_vulkan_PipelineDef_verify_table(flatcc_table_verifier_descriptor_t *td);
static int iree_hal_vulkan_ExecutableDef_verify_table(flatcc_table_verifier_descriptor_t *td);

static inline int iree_hal_vulkan_PushConstantRange_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, iree_hal_vulkan_PushConstantRange_identifier, 12, 4);
}

static inline int iree_hal_vulkan_PushConstantRange_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root_with_size(buf, bufsiz, iree_hal_vulkan_PushConstantRange_identifier, 12, 4);
}

static inline int iree_hal_vulkan_PushConstantRange_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, iree_hal_vulkan_PushConstantRange_type_hash, 12, 4);
}

static inline int iree_hal_vulkan_PushConstantRange_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root_with_size(buf, bufsiz, iree_hal_vulkan_PushConstantRange_type_hash, 12, 4);
}

static inline int iree_hal_vulkan_PushConstantRange_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 12, 4);
}

static inline int iree_hal_vulkan_PushConstantRange_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root_with_size(buf, bufsiz, thash, 12, 4);
}

static inline int iree_hal_vulkan_PushConstantRange_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 12, 4);
}

static inline int iree_hal_vulkan_PushConstantRange_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root_with_size(buf, bufsiz, fid, 12, 4);
}

static int iree_hal_vulkan_DescriptorSetLayoutBindingDef_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 4, 4) /* binding */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 4, 4) /* descriptor_type */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 4, 4) /* descriptor_count */)) return ret;
    if ((ret = flatcc_verify_field(td, 3, 4, 4) /* stage_flags */)) return ret;
    return flatcc_verify_ok;
}

static inline int iree_hal_vulkan_DescriptorSetLayoutBindingDef_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, iree_hal_vulkan_DescriptorSetLayoutBindingDef_identifier, &iree_hal_vulkan_DescriptorSetLayoutBindingDef_verify_table);
}

static inline int iree_hal_vulkan_DescriptorSetLayoutBindingDef_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, iree_hal_vulkan_DescriptorSetLayoutBindingDef_identifier, &iree_hal_vulkan_DescriptorSetLayoutBindingDef_verify_table);
}

static inline int iree_hal_vulkan_DescriptorSetLayoutBindingDef_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, iree_hal_vulkan_DescriptorSetLayoutBindingDef_type_identifier, &iree_hal_vulkan_DescriptorSetLayoutBindingDef_verify_table);
}

static inline int iree_hal_vulkan_DescriptorSetLayoutBindingDef_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, iree_hal_vulkan_DescriptorSetLayoutBindingDef_type_identifier, &iree_hal_vulkan_DescriptorSetLayoutBindingDef_verify_table);
}

static inline int iree_hal_vulkan_DescriptorSetLayoutBindingDef_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &iree_hal_vulkan_DescriptorSetLayoutBindingDef_verify_table);
}

static inline int iree_hal_vulkan_DescriptorSetLayoutBindingDef_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &iree_hal_vulkan_DescriptorSetLayoutBindingDef_verify_table);
}

static inline int iree_hal_vulkan_DescriptorSetLayoutBindingDef_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &iree_hal_vulkan_DescriptorSetLayoutBindingDef_verify_table);
}

static inline int iree_hal_vulkan_DescriptorSetLayoutBindingDef_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &iree_hal_vulkan_DescriptorSetLayoutBindingDef_verify_table);
}

static int iree_hal_vulkan_DescriptorSetLayoutDef_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_table_vector_field(td, 0, 0, &iree_hal_vulkan_DescriptorSetLayoutBindingDef_verify_table) /* bindings */)) return ret;
    return flatcc_verify_ok;
}

static inline int iree_hal_vulkan_DescriptorSetLayoutDef_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, iree_hal_vulkan_DescriptorSetLayoutDef_identifier, &iree_hal_vulkan_DescriptorSetLayoutDef_verify_table);
}

static inline int iree_hal_vulkan_DescriptorSetLayoutDef_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, iree_hal_vulkan_DescriptorSetLayoutDef_identifier, &iree_hal_vulkan_DescriptorSetLayoutDef_verify_table);
}

static inline int iree_hal_vulkan_DescriptorSetLayoutDef_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, iree_hal_vulkan_DescriptorSetLayoutDef_type_identifier, &iree_hal_vulkan_DescriptorSetLayoutDef_verify_table);
}

static inline int iree_hal_vulkan_DescriptorSetLayoutDef_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, iree_hal_vulkan_DescriptorSetLayoutDef_type_identifier, &iree_hal_vulkan_DescriptorSetLayoutDef_verify_table);
}

static inline int iree_hal_vulkan_DescriptorSetLayoutDef_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &iree_hal_vulkan_DescriptorSetLayoutDef_verify_table);
}

static inline int iree_hal_vulkan_DescriptorSetLayoutDef_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &iree_hal_vulkan_DescriptorSetLayoutDef_verify_table);
}

static inline int iree_hal_vulkan_DescriptorSetLayoutDef_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &iree_hal_vulkan_DescriptorSetLayoutDef_verify_table);
}

static inline int iree_hal_vulkan_DescriptorSetLayoutDef_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &iree_hal_vulkan_DescriptorSetLayoutDef_verify_table);
}

static int iree_hal_vulkan_PipelineLayoutDef_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_vector_field(td, 0, 0, 4, 4, INT64_C(1073741823)) /* descriptor_set_layout_ordinals */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 1, 0, 12, 4, INT64_C(357913941)) /* push_constant_ranges */)) return ret;
    return flatcc_verify_ok;
}

static inline int iree_hal_vulkan_PipelineLayoutDef_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, iree_hal_vulkan_PipelineLayoutDef_identifier, &iree_hal_vulkan_PipelineLayoutDef_verify_table);
}

static inline int iree_hal_vulkan_PipelineLayoutDef_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, iree_hal_vulkan_PipelineLayoutDef_identifier, &iree_hal_vulkan_PipelineLayoutDef_verify_table);
}

static inline int iree_hal_vulkan_PipelineLayoutDef_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, iree_hal_vulkan_PipelineLayoutDef_type_identifier, &iree_hal_vulkan_PipelineLayoutDef_verify_table);
}

static inline int iree_hal_vulkan_PipelineLayoutDef_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, iree_hal_vulkan_PipelineLayoutDef_type_identifier, &iree_hal_vulkan_PipelineLayoutDef_verify_table);
}

static inline int iree_hal_vulkan_PipelineLayoutDef_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &iree_hal_vulkan_PipelineLayoutDef_verify_table);
}

static inline int iree_hal_vulkan_PipelineLayoutDef_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &iree_hal_vulkan_PipelineLayoutDef_verify_table);
}

static inline int iree_hal_vulkan_PipelineLayoutDef_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &iree_hal_vulkan_PipelineLayoutDef_verify_table);
}

static inline int iree_hal_vulkan_PipelineLayoutDef_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &iree_hal_vulkan_PipelineLayoutDef_verify_table);
}

static int iree_hal_vulkan_ShaderModuleDef_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_vector_field(td, 0, 0, 4, 4, INT64_C(1073741823)) /* spirv_code */)) return ret;
    return flatcc_verify_ok;
}

static inline int iree_hal_vulkan_ShaderModuleDef_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, iree_hal_vulkan_ShaderModuleDef_identifier, &iree_hal_vulkan_ShaderModuleDef_verify_table);
}

static inline int iree_hal_vulkan_ShaderModuleDef_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, iree_hal_vulkan_ShaderModuleDef_identifier, &iree_hal_vulkan_ShaderModuleDef_verify_table);
}

static inline int iree_hal_vulkan_ShaderModuleDef_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, iree_hal_vulkan_ShaderModuleDef_type_identifier, &iree_hal_vulkan_ShaderModuleDef_verify_table);
}

static inline int iree_hal_vulkan_ShaderModuleDef_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, iree_hal_vulkan_ShaderModuleDef_type_identifier, &iree_hal_vulkan_ShaderModuleDef_verify_table);
}

static inline int iree_hal_vulkan_ShaderModuleDef_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &iree_hal_vulkan_ShaderModuleDef_verify_table);
}

static inline int iree_hal_vulkan_ShaderModuleDef_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &iree_hal_vulkan_ShaderModuleDef_verify_table);
}

static inline int iree_hal_vulkan_ShaderModuleDef_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &iree_hal_vulkan_ShaderModuleDef_verify_table);
}

static inline int iree_hal_vulkan_ShaderModuleDef_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &iree_hal_vulkan_ShaderModuleDef_verify_table);
}

static int iree_hal_vulkan_PipelineDef_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 4, 4) /* shader_module_ordinal */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* entry_point */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 4, 4) /* pipeline_layout_ordinal */)) return ret;
    if ((ret = flatcc_verify_field(td, 3, 4, 4) /* subgroup_size */)) return ret;
    if ((ret = flatcc_verify_table_field(td, 4, 0, &iree_hal_debug_ExportDef_verify_table) /* debug_info */)) return ret;
    return flatcc_verify_ok;
}

static inline int iree_hal_vulkan_PipelineDef_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, iree_hal_vulkan_PipelineDef_identifier, &iree_hal_vulkan_PipelineDef_verify_table);
}

static inline int iree_hal_vulkan_PipelineDef_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, iree_hal_vulkan_PipelineDef_identifier, &iree_hal_vulkan_PipelineDef_verify_table);
}

static inline int iree_hal_vulkan_PipelineDef_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, iree_hal_vulkan_PipelineDef_type_identifier, &iree_hal_vulkan_PipelineDef_verify_table);
}

static inline int iree_hal_vulkan_PipelineDef_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, iree_hal_vulkan_PipelineDef_type_identifier, &iree_hal_vulkan_PipelineDef_verify_table);
}

static inline int iree_hal_vulkan_PipelineDef_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &iree_hal_vulkan_PipelineDef_verify_table);
}

static inline int iree_hal_vulkan_PipelineDef_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &iree_hal_vulkan_PipelineDef_verify_table);
}

static inline int iree_hal_vulkan_PipelineDef_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &iree_hal_vulkan_PipelineDef_verify_table);
}

static inline int iree_hal_vulkan_PipelineDef_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &iree_hal_vulkan_PipelineDef_verify_table);
}

static int iree_hal_vulkan_ExecutableDef_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_table_vector_field(td, 0, 0, &iree_hal_vulkan_PipelineDef_verify_table) /* pipelines */)) return ret;
    if ((ret = flatcc_verify_table_vector_field(td, 1, 0, &iree_hal_vulkan_DescriptorSetLayoutDef_verify_table) /* descriptor_set_layouts */)) return ret;
    if ((ret = flatcc_verify_table_vector_field(td, 2, 0, &iree_hal_vulkan_PipelineLayoutDef_verify_table) /* pipeline_layouts */)) return ret;
    if ((ret = flatcc_verify_table_vector_field(td, 3, 0, &iree_hal_vulkan_ShaderModuleDef_verify_table) /* shader_modules */)) return ret;
    if ((ret = flatcc_verify_table_vector_field(td, 4, 0, &iree_hal_debug_SourceFileDef_verify_table) /* source_files */)) return ret;
    return flatcc_verify_ok;
}

static inline int iree_hal_vulkan_ExecutableDef_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, iree_hal_vulkan_ExecutableDef_identifier, &iree_hal_vulkan_ExecutableDef_verify_table);
}

static inline int iree_hal_vulkan_ExecutableDef_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, iree_hal_vulkan_ExecutableDef_identifier, &iree_hal_vulkan_ExecutableDef_verify_table);
}

static inline int iree_hal_vulkan_ExecutableDef_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, iree_hal_vulkan_ExecutableDef_type_identifier, &iree_hal_vulkan_ExecutableDef_verify_table);
}

static inline int iree_hal_vulkan_ExecutableDef_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, iree_hal_vulkan_ExecutableDef_type_identifier, &iree_hal_vulkan_ExecutableDef_verify_table);
}

static inline int iree_hal_vulkan_ExecutableDef_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &iree_hal_vulkan_ExecutableDef_verify_table);
}

static inline int iree_hal_vulkan_ExecutableDef_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &iree_hal_vulkan_ExecutableDef_verify_table);
}

static inline int iree_hal_vulkan_ExecutableDef_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &iree_hal_vulkan_ExecutableDef_verify_table);
}

static inline int iree_hal_vulkan_ExecutableDef_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &iree_hal_vulkan_ExecutableDef_verify_table);
}

#include "flatcc/flatcc_epilogue.h"
#endif /* VULKAN_EXECUTABLE_DEF_VERIFIER_H */
